namespace L2Dn.GameServer.Model.Effects;

[Flags]
public enum EffectFlags: long
{
    NONE = 0,

    RESURRECTION_SPECIAL = 1L << 0,
    NOBLESS_BLESSING = 1L << 1,
    SILENT_MOVE = 1L << 2,
    PROTECTION_BLESSING = 1L << 3,
    RELAXING = 1L << 4,
    BLOCK_CONTROL = 1L << 5,
    CONFUSED = 1L << 6,
    MUTED = 1L << 7,
    PSYCHICAL_MUTED = 1L << 8,
    PSYCHICAL_ATTACK_MUTED = 1L << 9,
    PASSIVE = 1L << 10,
    DISARMED = 1L << 11,
    ROOTED = 1L << 12,
    BLOCK_ACTIONS = 1L << 13,
    CONDITIONAL_BLOCK_ACTIONS = 1L << 14,
    BETRAYED = 1L << 15,
    HP_BLOCK = 1L << 16,
    MP_BLOCK = 1L << 17,
    BUFF_BLOCK = 1L << 18,
    DEBUFF_BLOCK = 1L << 19,
    ABNORMAL_SHIELD = 1L << 20,
    BLOCK_RESURRECTION = 1L << 21,
    UNTARGETABLE = 1L << 22,
    CANNOT_ESCAPE = 1L << 23,
    DOUBLE_CAST = 1L << 24,
    ATTACK_BEHIND = 1L << 25,
    TARGETING_DISABLED = 1L << 26,
    FACEOFF = 1L << 27,
    PHYSICAL_SHIELD_ANGLE_ALL = 1L << 28,
    CHEAPSHOT = 1L << 29,
    IGNORE_DEATH = 1L << 30,
    HPCPHEAL_CRITICAL = 1L << 31,
    PROTECT_DEATH_PENALTY = 1L << 32,
    CHAT_BLOCK = 1L << 33,
    FAKE_DEATH = 1L << 34,
    DUELIST_FURY = 1L << 35,
    FEAR = 1L << 36,
}