namespace L2Dn.Model.Enums;

/// <summary>
/// Enum of basic stats.
/// </summary>
public enum Stat
{
	// HP, MP & CP
	HP_LIMIT,
	MAX_HP,
	MAX_MP,
	MAX_CP,
	MAX_RECOVERABLE_HP, // The maximum HP that is able to be recovered trough heals
	MAX_RECOVERABLE_MP,
	MAX_RECOVERABLE_CP,
	REGENERATE_HP_RATE,
	REGENERATE_CP_RATE,
	REGENERATE_MP_RATE,
	ADDITIONAL_POTION_HP,
	ADDITIONAL_POTION_MP,
	ADDITIONAL_POTION_CP,
	MANA_CHARGE,
	HEAL_EFFECT,
	HEAL_EFFECT_ADD,
	FEED_MODIFY,

	// ATTACK & DEFENCE
	PHYSICAL_DEFENCE,
	MAGICAL_DEFENCE,
	PHYSICAL_ATTACK,
	MAGIC_ATTACK,
	WEAPON_BONUS_PHYSICAL_ATTACK,
	WEAPON_BONUS_PHYSICAL_ATTACK_MULTIPIER,
	WEAPON_BONUS_MAGIC_ATTACK,
	WEAPON_BONUS_MAGIC_ATTACK_MULTIPIER,
	MAGIC_ATTACK_BY_PHYSICAL_ATTACK,
	PHYSICAL_ATTACK_SPEED,
	MAGIC_ATTACK_SPEED, // Magic Skill Casting Time Rate
	ATK_REUSE, // Bows Hits Reuse Rate
	SHIELD_DEFENCE,
	SHIELD_DEFENCE_IGNORE_REMOVAL,
	SHIELD_DEFENCE_IGNORE_REMOVAL_ADD,
	CRITICAL_DAMAGE,
	CRITICAL_DAMAGE_ADD, // this is another type for special critical damage mods - vicious stance, critical power and critical damage SA
	HATE_ATTACK,
	REAR_DAMAGE_RATE,
	AUTO_ATTACK_DAMAGE_BONUS,
	IGNORE_REDUCE_DAMAGE,

	// ELEMENTAL SPIRITS
	ELEMENTAL_SPIRIT_FIRE_ATTACK,
	ELEMENTAL_SPIRIT_WATER_ATTACK,
	ELEMENTAL_SPIRIT_WIND_ATTACK,
	ELEMENTAL_SPIRIT_EARTH_ATTACK,
	ELEMENTAL_SPIRIT_FIRE_DEFENSE,
	ELEMENTAL_SPIRIT_WATER_DEFENSE,
	ELEMENTAL_SPIRIT_WIND_DEFENSE,
	ELEMENTAL_SPIRIT_EARTH_DEFENSE,
	ELEMENTAL_SPIRIT_CRITICAL_RATE,
	ELEMENTAL_SPIRIT_CRITICAL_DAMAGE,
	ELEMENTAL_SPIRIT_BONUS_EXP,

	// PVP BONUS
	PVP_PHYSICAL_ATTACK_DAMAGE,
	PVP_MAGICAL_SKILL_DAMAGE,
	PVP_PHYSICAL_SKILL_DAMAGE,
	PVP_PHYSICAL_ATTACK_DEFENCE,
	PVP_MAGICAL_SKILL_DEFENCE,
	PVP_PHYSICAL_SKILL_DEFENCE,

	// PVE BONUS
	PVE_PHYSICAL_ATTACK_DAMAGE,
	PVE_PHYSICAL_SKILL_DAMAGE,
	PVE_MAGICAL_SKILL_DAMAGE,
	PVE_PHYSICAL_ATTACK_DEFENCE,
	PVE_PHYSICAL_SKILL_DEFENCE,
	PVE_MAGICAL_SKILL_DEFENCE,
	PVE_RAID_PHYSICAL_ATTACK_DAMAGE,
	PVE_RAID_PHYSICAL_SKILL_DAMAGE,
	PVE_RAID_MAGICAL_SKILL_DAMAGE,
	PVE_RAID_PHYSICAL_ATTACK_DEFENCE,
	PVE_RAID_PHYSICAL_SKILL_DEFENCE,
	PVE_RAID_MAGICAL_SKILL_DEFENCE,

	// FIXED BONUS
	PVP_DAMAGE_TAKEN,
	PVE_DAMAGE_TAKEN,
	PVE_DAMAGE_TAKEN_MONSTER,
	PVE_DAMAGE_TAKEN_RAID,

	// ATTACK & DEFENCE RATES
	MAGIC_CRITICAL_DAMAGE,
	SKILL_POWER_ADD,
	PHYSICAL_SKILL_POWER,
	MAGICAL_SKILL_POWER,
	PHYSICAL_SKILL_CRITICAL_DAMAGE,
	PHYSICAL_SKILL_CRITICAL_DAMAGE_ADD,
	MAGIC_CRITICAL_DAMAGE_ADD,
	SHIELD_DEFENCE_RATE,
	CRITICAL_RATE,
	CRITICAL_RATE_SKILL,
	ADD_MAX_MAGIC_CRITICAL_RATE,
	ADD_MAX_PHYSICAL_CRITICAL_RATE,
	MAGIC_CRITICAL_RATE,
	MAGIC_CRITICAL_RATE_BY_CRITICAL_RATE,
	DEFENCE_CRITICAL_RATE,
	DEFENCE_CRITICAL_RATE_ADD,
	DEFENCE_MAGIC_CRITICAL_RATE,
	DEFENCE_MAGIC_CRITICAL_RATE_ADD,
	DEFENCE_CRITICAL_DAMAGE,
	DEFENCE_MAGIC_CRITICAL_DAMAGE,
	DEFENCE_MAGIC_CRITICAL_DAMAGE_ADD,
	DEFENCE_CRITICAL_DAMAGE_ADD, // Resistance to critical damage in value (Example: +100 will be 100 more critical damage, NOT 100% more).
	DEFENCE_PHYSICAL_SKILL_CRITICAL_DAMAGE,
	DEFENCE_PHYSICAL_SKILL_CRITICAL_DAMAGE_ADD,
	DEFENCE_PHYSICAL_SKILL_CRITICAL_RATE,
	DEFENCE_PHYSICAL_SKILL_CRITICAL_RATE_ADD,
	DEFENCE_IGNORE_REMOVAL,
	DEFENCE_IGNORE_REMOVAL_ADD,
	AREA_OF_EFFECT_DAMAGE_DEFENCE,
	AREA_OF_EFFECT_DAMAGE_MODIFY,
	BLOW_RATE,
	BLOW_RATE_DEFENCE,
	INSTANT_KILL_RESIST,
	EXPSP_RATE,
	ACTIVE_BONUS_EXP, // Used to measure active skill bonus exp.
	BONUS_EXP_BUFFS, // Used to count active skill exp.
	BONUS_EXP_PASSIVES, // Used to count passive skill exp.
	BONUS_EXP_PET,
	BONUS_EXP,
	BONUS_SP,
	BONUS_DROP_ADENA,
	BONUS_DROP_AMOUNT,
	BONUS_DROP_RATE,
	BONUS_DROP_RATE_LCOIN,
	BONUS_SPOIL_RATE,
	BONUS_RAID_POINTS,
	ATTACK_CANCEL,

	// ACCURACY & RANGE
	ACCURACY_COMBAT,
	ACCURACY_MAGIC,
	EVASION_RATE,
	MAGIC_EVASION_RATE,
	PHYSICAL_ATTACK_RANGE,
	MAGIC_ATTACK_RANGE,
	ATTACK_COUNT_MAX,
	PHYSICAL_POLEARM_TARGET_SINGLE,
	WEAPON_ATTACK_ANGLE_BONUS,

	// Run speed, walk & escape speed are calculated proportionally, magic speed is a buff
	MOVE_SPEED,
	SPEED_LIMIT,
	RUN_SPEED,
	WALK_SPEED,
	SWIM_RUN_SPEED,
	SWIM_WALK_SPEED,
	FLY_RUN_SPEED,
	FLY_WALK_SPEED,

	// BASIC STATS
	STAT_STR,
	STAT_CON,
	STAT_DEX,
	STAT_INT,
	STAT_WIT,
	STAT_MEN,

	// Special stats, share one slot in Calculator

	// VARIOUS
	BREATH,
	FALL,
	FISHING_EXP_SP_BONUS,
	ENCHANT_RATE,

	// VULNERABILITIES
	DAMAGE_ZONE_VULN,
	RESIST_DISPEL_BUFF, // Resistance for cancel type skills
	RESIST_ABNORMAL_DEBUFF,

	// RESISTANCES
	FIRE_RES,
	WIND_RES,
	WATER_RES,
	EARTH_RES,
	HOLY_RES,
	DARK_RES,
	BASE_ATTRIBUTE_RES,
	MAGIC_SUCCESS_RES,

	// new StatInfo(Stat.BUFF_IMMUNITY, "buffImmunity"), // TODO: Implement me
	ABNORMAL_RESIST_PHYSICAL,
	ABNORMAL_RESIST_MAGICAL,
	REAL_DAMAGE_RESIST,

	// ELEMENT POWER
	FIRE_POWER,
	WATER_POWER,
	WIND_POWER,
	EARTH_POWER,
	HOLY_POWER,
	DARK_POWER,

	// PROFICIENCY
	REFLECT_DAMAGE_PERCENT,
	REFLECT_DAMAGE_PERCENT_DEFENSE,
	REFLECT_SKILL_MAGIC, // Need rework
	REFLECT_SKILL_PHYSIC, // Need rework
	VENGEANCE_SKILL_MAGIC_DAMAGE,
	VENGEANCE_SKILL_PHYSICAL_DAMAGE,
	ABSORB_DAMAGE_PERCENT,
	ABSORB_DAMAGE_CHANCE,
	ABSORB_DAMAGE_DEFENCE,
	TRANSFER_DAMAGE_SUMMON_PERCENT,
	MANA_SHIELD_PERCENT,
	TRANSFER_DAMAGE_TO_PLAYER,
	ABSORB_MANA_DAMAGE_PERCENT,
	ABSORB_MANA_DAMAGE_CHANCE,

	WEIGHT_LIMIT,
	WEIGHT_PENALTY,

	// ExSkill
	INVENTORY_NORMAL,
	STORAGE_PRIVATE,
	TRADE_SELL,
	TRADE_BUY,
	RECIPE_DWARVEN,
	RECIPE_COMMON,

	// Skill mastery
	SKILL_MASTERY,
	SKILL_MASTERY_RATE,

	// Vitality
	VITALITY_CONSUME_RATE,
	VITALITY_EXP_RATE,
	VITALITY_SKILLS, // Used to count vitality skill bonuses.

	// Magic Lamp
	MAGIC_LAMP_EXP_RATE,

	LAMP_BONUS_EXP,
	LAMP_BONUS_BUFFS_COUNT,

	// Henna
	HENNA_SLOTS_AVAILABLE,

	// Souls
	MAX_SOULS,

	REDUCE_EXP_LOST_BY_PVP,
	REDUCE_EXP_LOST_BY_MOB,
	REDUCE_EXP_LOST_BY_RAID,

	REDUCE_DEATH_PENALTY_BY_PVP,
	REDUCE_DEATH_PENALTY_BY_MOB,
	REDUCE_DEATH_PENALTY_BY_RAID,

	// Brooches
	BROOCH_JEWELS,

	// Agathions
	AGATHION_SLOTS,

	// Artifacts
	ARTIFACT_SLOTS,

	// Summon Points
	MAX_SUMMON_POINTS,

	// Cubic Count
	MAX_CUBIC,

	// The maximum allowed range to be damaged/debuffed from.
	SPHERIC_BARRIER_RANGE,

	// Blocks given amount of debuffs.
	DEBUFF_BLOCK,

	// Affects the random weapon damage.
	RANDOM_DAMAGE,

	// Affects the random weapon damage.
	DAMAGE_LIMIT,

	// Maximun momentum one can charge
	MAX_MOMENTUM,

	// Which base stat ordinal should alter skill critical formula.
	STAT_BONUS_SKILL_CRITICAL,
	STAT_BONUS_SPEED,
	CRAFTING_CRITICAL,
	SHOTS_BONUS,
	SOULSHOT_RESISTANCE,
	SPIRITSHOT_RESISTANCE,
	WORLD_CHAT_POINTS,
	ATTACK_DAMAGE,

	IMMOBILE_DAMAGE_BONUS,
	IMMOBILE_DAMAGE_RESIST,

	CRAFT_RATE,
	ELIXIR_USAGE_LIMIT,
	RESURRECTION_FEE_MODIFIER
}