namespace L2Dn.GameServer.Enums;

public enum MailType
{
    REGULAR,
    NEWS_INFORMER,
    NPC,
    BIRTHDAY,
    COMMISSION_ITEM_RETURNED,
    COMMISSION_ITEM_SOLD,
    MENTOR_NPC,
    PRIME_SHOP_GIFT,
    PURGE_REWARD,
    BALOK_RANKING_REWARD,
    PLEDGE_DONATION_CRITICAL_SUCCESS
}