using L2Dn.GameServer.Model.ItemContainers;

namespace L2Dn.GameServer.Enums;

public enum InventorySlot
{
	UNDER,
	REAR,
	LEAR,
	NECK,
	RFINGER,
	LFINGER,
	HEAD,
	RHAND,
	LHAND,
	GLOVES,
	CHEST,
	LEGS,
	FEET,
	CLOAK,
	LRHAND,
	HAIR,
	HAIR2,
	RBRACELET,
	LBRACELET,
	AGATHION1,
	AGATHION2,
	AGATHION3,
	AGATHION4,
	AGATHION5,
	DECO1,
	DECO2,
	DECO3,
	DECO4,
	DECO5,
	DECO6,
	BELT,
	BROOCH,
	BROOCH_JEWEL,
	BROOCH_JEWEL2,
	BROOCH_JEWEL3,
	BROOCH_JEWEL4,
	BROOCH_JEWEL5,
	BROOCH_JEWEL6,
	ARTIFACT_BOOK,
	ARTIFACT1,
	ARTIFACT2,
	ARTIFACT3,
	ARTIFACT4,
	ARTIFACT5,
	ARTIFACT6,
	ARTIFACT7,
	ARTIFACT8,
	ARTIFACT9,
	ARTIFACT10,
	ARTIFACT11,
	ARTIFACT12,
	ARTIFACT13,
	ARTIFACT14,
	ARTIFACT15,
	ARTIFACT16,
	ARTIFACT17,
	ARTIFACT18,
	ARTIFACT19,
	ARTIFACT20,
	ARTIFACT21
}

public static class InventorySlotUtil
{
    private static readonly int[] _paperdollOrder =
    [
	    Inventory.PAPERDOLL_UNDER,
	    Inventory.PAPERDOLL_REAR,
	    Inventory.PAPERDOLL_LEAR,
	    Inventory.PAPERDOLL_NECK,
	    Inventory.PAPERDOLL_RFINGER,
	    Inventory.PAPERDOLL_LFINGER,
	    Inventory.PAPERDOLL_HEAD,
	    Inventory.PAPERDOLL_RHAND,
	    Inventory.PAPERDOLL_LHAND,
	    Inventory.PAPERDOLL_GLOVES,
	    Inventory.PAPERDOLL_CHEST,
	    Inventory.PAPERDOLL_LEGS,
	    Inventory.PAPERDOLL_FEET,
	    Inventory.PAPERDOLL_CLOAK,
	    Inventory.PAPERDOLL_RHAND,
	    Inventory.PAPERDOLL_HAIR,
	    Inventory.PAPERDOLL_HAIR2,
	    Inventory.PAPERDOLL_RBRACELET,
	    Inventory.PAPERDOLL_LBRACELET,
	    Inventory.PAPERDOLL_AGATHION1,
	    Inventory.PAPERDOLL_AGATHION2,
	    Inventory.PAPERDOLL_AGATHION3,
	    Inventory.PAPERDOLL_AGATHION4,
	    Inventory.PAPERDOLL_AGATHION5,
	    Inventory.PAPERDOLL_DECO1,
	    Inventory.PAPERDOLL_DECO2,
	    Inventory.PAPERDOLL_DECO3,
	    Inventory.PAPERDOLL_DECO4,
	    Inventory.PAPERDOLL_DECO5,
	    Inventory.PAPERDOLL_DECO6,
	    Inventory.PAPERDOLL_BELT,
	    Inventory.PAPERDOLL_BROOCH,
	    Inventory.PAPERDOLL_BROOCH_JEWEL1,
	    Inventory.PAPERDOLL_BROOCH_JEWEL2,
	    Inventory.PAPERDOLL_BROOCH_JEWEL3,
	    Inventory.PAPERDOLL_BROOCH_JEWEL4,
	    Inventory.PAPERDOLL_BROOCH_JEWEL5,
	    Inventory.PAPERDOLL_BROOCH_JEWEL6,
	    Inventory.PAPERDOLL_ARTIFACT_BOOK,
	    Inventory.PAPERDOLL_ARTIFACT1,
	    Inventory.PAPERDOLL_ARTIFACT2,
	    Inventory.PAPERDOLL_ARTIFACT3,
	    Inventory.PAPERDOLL_ARTIFACT4,
	    Inventory.PAPERDOLL_ARTIFACT5,
	    Inventory.PAPERDOLL_ARTIFACT6,
	    Inventory.PAPERDOLL_ARTIFACT7,
	    Inventory.PAPERDOLL_ARTIFACT8,
	    Inventory.PAPERDOLL_ARTIFACT9,
	    Inventory.PAPERDOLL_ARTIFACT10,
	    Inventory.PAPERDOLL_ARTIFACT11,
	    Inventory.PAPERDOLL_ARTIFACT12,
	    Inventory.PAPERDOLL_ARTIFACT13,
	    Inventory.PAPERDOLL_ARTIFACT14,
	    Inventory.PAPERDOLL_ARTIFACT15,
	    Inventory.PAPERDOLL_ARTIFACT16,
	    Inventory.PAPERDOLL_ARTIFACT17,
	    Inventory.PAPERDOLL_ARTIFACT18,
	    Inventory.PAPERDOLL_ARTIFACT19,
	    Inventory.PAPERDOLL_ARTIFACT20,
	    Inventory.PAPERDOLL_ARTIFACT21
    ];

    public static int GetPaperdollSlot(this InventorySlot slot)
    {
	    int index = (int)slot;
	    if (index >= 0 && index < _paperdollOrder.Length)
		    return _paperdollOrder[index];

	    throw new ArgumentOutOfRangeException();
    }
}