namespace L2Dn.GameServer.Enums;

public enum MatchingMemberType
{
    WAITING_PLAYER,
    PARTY_LEADER,
    PARTY_MEMBER,
    COMMAND_CHANNEL_LEADER,
    COMMAND_CHANNEL_PARTY_MEMBER,
    WAITING_PARTY,
    WAITING_PLAYER_NO_PARTY
}