using L2Dn.GameServer.Network.IncomingPackets;
using L2Dn.GameServer.Network.IncomingPackets.AutoPlay;
using L2Dn.GameServer.Network.IncomingPackets.CastleWar;
using L2Dn.GameServer.Network.IncomingPackets.ClassChange;
using L2Dn.GameServer.Network.IncomingPackets.Collections;
using L2Dn.GameServer.Network.IncomingPackets.DailyMissions;
using L2Dn.GameServer.Network.IncomingPackets.Enchanting;
using L2Dn.GameServer.Network.IncomingPackets.Friends;
using L2Dn.GameServer.Network.IncomingPackets.HuntingZones;
using L2Dn.GameServer.Network.IncomingPackets.LimitShop;
using L2Dn.GameServer.Network.IncomingPackets.NewHenna;
using L2Dn.GameServer.Network.IncomingPackets.Pets;
using L2Dn.GameServer.Network.IncomingPackets.Ranking;
using L2Dn.GameServer.Network.IncomingPackets.Settings;
using L2Dn.GameServer.Network.IncomingPackets.SteadyBox;
using L2Dn.GameServer.Network.IncomingPackets.Teleports;
using L2Dn.GameServer.Network.OutgoingPackets;
using L2Dn.Network;
using L2Dn.Packets;

namespace L2Dn.GameServer.Network;

internal sealed class GamePacketHandler: PacketHandler<GameSession>
{
    public GamePacketHandler()
    {
        SetDefaultAllowedStates(GameSessionState.InGame);
        
        /* 00 */ RegisterPacket<LogoutPacket>(IncomingPacketCodes.LOGOUT).WithAllowedStates(GameSessionState.InGame | GameSessionState.CharacterScreen);
        /* 01 */ RegisterPacket<AttackRequestPacket>(IncomingPacketCodes.ATTACK);
        /* 03 */ RegisterPacket<RequestStartPledgeWarPacket>(IncomingPacketCodes.REQUEST_START_PLEDGE_WAR);
        /* 04 */ RegisterPacket<RequestReplyStartPledgeWarPacket>(IncomingPacketCodes.REQUEST_REPLY_START_PLEDGE);
        /* 05 */ RegisterPacket<RequestStopPledgeWarPacket>(IncomingPacketCodes.REQUEST_STOP_PLEDGE_WAR);
        /* 06 */ RegisterPacket<RequestReplyStopPledgeWarPacket>(IncomingPacketCodes.REQUEST_REPLY_STOP_PLEDGE_WAR);
        /* 07 */ RegisterPacket<RequestSurrenderPledgeWarPacket>(IncomingPacketCodes.REQUEST_SURRENDER_PLEDGE_WAR);
        /* 08 */ RegisterPacket<RequestReplySurrenderPledgeWarPacket>(IncomingPacketCodes.REQUEST_REPLY_SURRENDER_PLEDGE_WAR);
        /* 09 */ RegisterPacket<RequestSetPledgeCrestPacket>(IncomingPacketCodes.REQUEST_SET_PLEDGE_CREST);
        /* 0B */ RegisterPacket<RequestGiveNickNamePacket>(IncomingPacketCodes.REQUEST_GIVE_NICK_NAME);
        /* 0C */ RegisterPacket<CharacterCreatePacket>(IncomingPacketCodes.CHARACTER_CREATE).WithAllowedStates(GameSessionState.CharacterScreen);
        /* 0D */ RegisterPacket<CharacterDeletePacket>(IncomingPacketCodes.CHARACTER_DELETE).WithAllowedStates(GameSessionState.CharacterScreen);
        /* 0E */ RegisterPacket<ProtocolVersionPacket>(IncomingPacketCodes.PROTOCOL_VERSION).WithAllowedStates(GameSessionState.ProtocolVersion);
        /* 0F */ RegisterPacket<RequestMovePacket>(IncomingPacketCodes.MOVE_BACKWARD_TO_LOCATION);
        /* 11 */ RegisterPacket<EnterWorldPacket>(IncomingPacketCodes.ENTER_WORLD).WithAllowedStates(GameSessionState.EnteringGame);
        /* 12 */ RegisterPacket<CharacterSelectPacket>(IncomingPacketCodes.CHARACTER_SELECT).WithAllowedStates(GameSessionState.CharacterScreen);
        /* 13 */ RegisterPacket<NewCharacterPacket>(IncomingPacketCodes.NEW_CHARACTER).WithAllowedStates(GameSessionState.CharacterScreen);
        /* 14 */ RegisterPacket<RequestItemListPacket>(IncomingPacketCodes.REQUEST_ITEM_LIST);
        /* 16 */ RegisterPacket<RequestUnEquipItemPacket>(IncomingPacketCodes.REQUEST_UN_EQUIP_ITEM);
        /* 17 */ RegisterPacket<RequestDropItemPacket>(IncomingPacketCodes.REQUEST_DROP_ITEM);
        /* 19 */ RegisterPacket<UseItemPacket>(IncomingPacketCodes.USE_ITEM);
        /* 1A */ RegisterPacket<TradeRequestPacket>(IncomingPacketCodes.TRADE_REQUEST);
        /* 1B */ RegisterPacket<AddTradeItemPacket>(IncomingPacketCodes.ADD_TRADE_ITEM);
        /* 1C */ RegisterPacket<TradeDoneRequestPacket>(IncomingPacketCodes.TRADE_DONE);
        /* 1F */ RegisterPacket<ActionPacket>(IncomingPacketCodes.ACTION);
        /* 22 */ RegisterPacket<RequestLinkHtmlPacket>(IncomingPacketCodes.REQUEST_LINK_HTML);
        /* 23 */ RegisterPacket<RequestBypassToServerPacket>(IncomingPacketCodes.REQUEST_BYPASS_TO_SERVER);
        /* 24 */ RegisterPacket<RequestBbsWritePacket>(IncomingPacketCodes.REQUEST_BBS_WRITE);
        /* 26 */ RegisterPacket<RequestJoinPledgePacket>(IncomingPacketCodes.REQUEST_JOIN_PLEDGE);
        /* 27 */ RegisterPacket<RequestAnswerJoinPledgePacket>(IncomingPacketCodes.REQUEST_ANSWER_JOIN_PLEDGE);
        /* 28 */ RegisterPacket<RequestWithdrawalPledgePacket>(IncomingPacketCodes.REQUEST_WITHDRAWAL_PLEDGE);
        /* 29 */ RegisterPacket<RequestOustPledgeMemberPacket>(IncomingPacketCodes.REQUEST_OUST_PLEDGE_MEMBER);
        /* 2B */ RegisterPacket<AuthLoginPacket>(IncomingPacketCodes.AUTH_LOGIN).WithAllowedStates(GameSessionState.Authorization);
        /* 2C */ RegisterPacket<RequestGetItemFromPetPacket>(IncomingPacketCodes.REQUEST_GET_ITEM_FROM_PET);
        /* 2E */ RegisterPacket<RequestAllyInfoPacket>(IncomingPacketCodes.REQUEST_ALLY_INFO);
        /* 2F */ RegisterPacket<RequestCrystallizeItemPacket>(IncomingPacketCodes.REQUEST_CRYSTALLIZE_ITEM);
        /* 30 */ RegisterPacket<RequestPrivateStoreManageSellPacket>(IncomingPacketCodes.REQUEST_PRIVATE_STORE_MANAGE_SELL);
        /* 31 */ RegisterPacket<SetPrivateStoreListSellPacket>(IncomingPacketCodes.SET_PRIVATE_STORE_LIST_SELL);
        /* 32 */ RegisterPacket<AttackRequestPacket>(IncomingPacketCodes.ATTACK_REQUEST);
        /* 37 */ RegisterPacket<RequestSellItemPacket>(IncomingPacketCodes.REQUEST_SELL_ITEM);
        /* 38 */ RegisterPacket<RequestMagicSkillListPacket>(IncomingPacketCodes.REQUEST_MAGIC_SKILL_LIST);
        /* 39 */ RegisterPacket<RequestMagicSkillUsePacket>(IncomingPacketCodes.REQUEST_MAGIC_SKILL_USE);
        /* 3A */ RegisterPacket<AppearingPacket>(IncomingPacketCodes.APPEARING);
        /* 3B */ RegisterPacket<SendWareHouseDepositListPacket>(IncomingPacketCodes.SEND_WARE_HOUSE_DEPOSIT_LIST);
        /* 3C */ RegisterPacket<SendWareHouseWithDrawListPacket>(IncomingPacketCodes.SEND_WARE_HOUSE_WITH_DRAW_LIST);
        /* 3D */ RegisterPacket<RequestShortCutRegisterPacket>(IncomingPacketCodes.REQUEST_SHORT_CUT_REG);
        /* 3F */ RegisterPacket<RequestShortCutDeletePacket>(IncomingPacketCodes.REQUEST_SHORT_CUT_DEL);
        /* 40 */ RegisterPacket<RequestBuyItemPacket>(IncomingPacketCodes.REQUEST_BUY_ITEM);
        /* 42 */ RegisterPacket<RequestJoinPartyPacket>(IncomingPacketCodes.REQUEST_JOIN_PARTY);
        /* 43 */ RegisterPacket<RequestAnswerJoinPartyPacket>(IncomingPacketCodes.REQUEST_ANSWER_JOIN_PARTY);
        /* 44 */ RegisterPacket<RequestWithdrawalPartyPacket>(IncomingPacketCodes.REQUEST_WITH_DRAWAL_PARTY);
        /* 45 */ RegisterPacket<RequestOustPartyMemberPacket>(IncomingPacketCodes.REQUEST_OUST_PARTY_MEMBER);
        /* 47 */ RegisterPacket<CannotMoveAnymorePacket>(IncomingPacketCodes.CANNOT_MOVE_ANYMORE);
        /* 48 */ RegisterPacket<RequestTargetCancelPacket>(IncomingPacketCodes.REQUEST_TARGET_CANCELD);
        /* 49 */ RegisterPacket<Say2Packet>(IncomingPacketCodes.SAY2);
        /* 4D */ RegisterPacket<RequestPledgeMemberListPacket>(IncomingPacketCodes.REQUEST_PLEDGE_MEMBER_LIST);
        /* 50 */ RegisterPacket<RequestSkillListPacket>(IncomingPacketCodes.REQUEST_SKILL_LIST);
        /* 52 */ RegisterPacket<MoveWithDeltaPacket>(IncomingPacketCodes.MOVE_WITH_DELTA);
        /* 53 */ RegisterPacket<RequestGetOnVehiclePacket>(IncomingPacketCodes.REQUEST_GET_ON_VEHICLE);
        /* 54 */ RegisterPacket<RequestGetOffVehiclePacket>(IncomingPacketCodes.REQUEST_GET_OFF_VEHICLE);
        /* 55 */ RegisterPacket<AnswerTradeRequestPacket>(IncomingPacketCodes.ANSWER_TRADE_REQUEST);
        /* 56 */ RegisterPacket<RequestActionUsePacket>(IncomingPacketCodes.REQUEST_ACTION_USE);
        /* 57 */ RegisterPacket<RequestRestartPacket>(IncomingPacketCodes.REQUEST_RESTART);
        /* 59 */ RegisterPacket<ValidatePositionPacket>(IncomingPacketCodes.VALIDATE_POSITION);
        /* 5B */ RegisterPacket<StartRotatingPacket>(IncomingPacketCodes.START_ROTATING);
        /* 5C */ RegisterPacket<FinishRotatingPacket>(IncomingPacketCodes.FINISH_ROTATING);
        /* 5E */ RegisterPacket<RequestShowBoardPacket>(IncomingPacketCodes.REQUEST_SHOW_BOARD);
        /* 5F */ RegisterPacket<RequestEnchantItemPacket>(IncomingPacketCodes.REQUEST_ENCHANT_ITEM);
        /* 60 */ RegisterPacket<RequestDestroyItemPacket>(IncomingPacketCodes.REQUEST_DESTROY_ITEM);
        /* 62 */ RegisterPacket<RequestQuestListPacket>(IncomingPacketCodes.REQUEST_QUEST_LIST).WithAllowedStates(GameSessionState.EnteringGame | GameSessionState.InGame);
        /* 63 */ RegisterPacket<RequestQuestAbortPacket>(IncomingPacketCodes.REQUEST_QUEST_ABORT);
        /* 65 */ RegisterPacket<RequestPledgeInfoPacket>(IncomingPacketCodes.REQUEST_PLEDGE_INFO);
        /* 66 */ RegisterPacket<RequestPledgeExtendedInfoPacket>(IncomingPacketCodes.REQUEST_PLEDGE_EXTENDED_INFO);
        /* 67 */ RegisterPacket<RequestPledgeCrestPacket>(IncomingPacketCodes.REQUEST_PLEDGE_CREST);
        /* 6B */ RegisterPacket<RequestSendFriendMsgPacket>(IncomingPacketCodes.REQUEST_SEND_FRIEND_MSG);
        /* 6C */ RegisterPacket<RequestShowMiniMapPacket>(IncomingPacketCodes.REQUEST_SHOW_MINI_MAP);
        /* 70 */ RegisterPacket<RequestHennaRemoveListPacket>(IncomingPacketCodes.REQUEST_HENNA_REMOVE_LIST);
        /* 71 */ RegisterPacket<RequestHennaItemRemoveInfoPacket>(IncomingPacketCodes.REQUEST_HENNA_ITEM_REMOVE_INFO);
        /* 73 */ RegisterPacket<RequestAcquireSkillInfoPacket>(IncomingPacketCodes.REQUEST_ACQUIRE_SKILL_INFO);
        /* 74 */ RegisterPacket<SendBypassBuildCmdPacket>(IncomingPacketCodes.SEND_BYPASS_BUILD_CMD);
        /* 75 */ RegisterPacket<RequestMoveToLocationInVehiclePacket>(IncomingPacketCodes.REQUEST_MOVE_TO_LOCATION_IN_VEHICLE);
        /* 76 */ RegisterPacket<CannotMoveAnymoreInVehiclePacket>(IncomingPacketCodes.CANNOT_MOVE_ANYMORE_IN_VEHICLE);
        /* 77 */ RegisterPacket<RequestFriendInvitePacket>(IncomingPacketCodes.REQUEST_FRIEND_INVITE);
        /* 78 */ RegisterPacket<RequestAnswerFriendInvitePacket>(IncomingPacketCodes.REQUEST_ANSWER_FRIEND_INVITE);
        /* 79 */ RegisterPacket<RequestFriendListPacket>(IncomingPacketCodes.REQUEST_FRIEND_LIST);
        /* 7A */ RegisterPacket<RequestFriendDelPacket>(IncomingPacketCodes.REQUEST_FRIEND_DEL);
        /* 7B */ RegisterPacket<CharacterRestorePacket>(IncomingPacketCodes.CHARACTER_RESTORE).WithAllowedStates(GameSessionState.CharacterScreen);
        /* 7C */ RegisterPacket<RequestAcquireSkillPacket>(IncomingPacketCodes.REQUEST_ACQUIRE_SKILL);
        /* 7D */ RegisterPacket<RequestRestartPointPacket>(IncomingPacketCodes.REQUEST_RESTART_POINT);
        /* 7E */ RegisterPacket<RequestGmCommandPacket>(IncomingPacketCodes.REQUEST_GM_COMMAND);
        /* 7F */ RegisterPacket<RequestPartyMatchConfigPacket>(IncomingPacketCodes.REQUEST_PARTY_MATCH_CONFIG);
        /* 80 */ RegisterPacket<RequestPartyMatchListPacket>(IncomingPacketCodes.REQUEST_PARTY_MATCH_LIST);
        /* 81 */ RegisterPacket<RequestPartyMatchDetailPacket>(IncomingPacketCodes.REQUEST_PARTY_MATCH_DETAIL);
        /* 83 */ RegisterPacket<RequestPrivateStoreBuyPacket>(IncomingPacketCodes.REQUEST_PRIVATE_STORE_BUY);
        /* 85 */ RegisterPacket<RequestTutorialLinkHtmlPacket>(IncomingPacketCodes.REQUEST_TUTORIAL_LINK_HTML);
        /* 86 */ RegisterPacket<RequestTutorialPassCmdToServerPacket>(IncomingPacketCodes.REQUEST_TUTORIAL_PASS_CMD_TO_SERVER);
        /* 87 */ RegisterPacket<RequestTutorialQuestionMarkPacket>(IncomingPacketCodes.REQUEST_TUTORIAL_QUESTION_MARK);
        /* 88 */ RegisterPacket<RequestTutorialClientEventPacket>(IncomingPacketCodes.REQUEST_TUTORIAL_CLIENT_EVENT);
        /* 89 */ RegisterPacket<RequestPetitionPacket>(IncomingPacketCodes.REQUEST_PETITION);
        /* 8A */ RegisterPacket<RequestPetitionCancelPacket>(IncomingPacketCodes.REQUEST_PETITION_CANCEL);
        /* 8B */ RegisterPacket<RequestGmListPacket>(IncomingPacketCodes.REQUEST_GM_LIST);
        /* 8C */ RegisterPacket<RequestJoinAllyPacket>(IncomingPacketCodes.REQUEST_JOIN_ALLY);
        /* 8D */ RegisterPacket<RequestAnswerJoinAllyPacket>(IncomingPacketCodes.REQUEST_ANSWER_JOIN_ALLY);
        /* 8E */ RegisterPacket<AllyLeavePacket>(IncomingPacketCodes.ALLY_LEAVE);
        /* 8F */ RegisterPacket<AllyDismissPacket>(IncomingPacketCodes.ALLY_DISMISS);
        /* 90 */ RegisterPacket<RequestDismissAllyPacket>(IncomingPacketCodes.REQUEST_DISMISS_ALLY);
        /* 91 */ RegisterPacket<RequestSetAllyCrestPacket>(IncomingPacketCodes.REQUEST_SET_ALLY_CREST);
        /* 92 */ RegisterPacket<RequestAllyCrestPacket>(IncomingPacketCodes.REQUEST_ALLY_CREST);
        /* 93 */ RegisterPacket<RequestChangePetNamePacket>(IncomingPacketCodes.REQUEST_CHANGE_PET_NAME);
        /* 94 */ RegisterPacket<RequestPetUseItemPacket>(IncomingPacketCodes.REQUEST_PET_USE_ITEM);
        /* 95 */ RegisterPacket<RequestGiveItemToPetPacket>(IncomingPacketCodes.REQUEST_GIVE_ITEM_TO_PET);
        // /* 96 */ RegisterPacket<RequestPrivateStoreQuitSellPacket>(IncomingPacketCodes.REQUEST_PRIVATE_STORE_QUIT_SELL);
        // /* 97 */ RegisterPacket<SetPrivateStoreMsgSellPacket>(IncomingPacketCodes.SET_PRIVATE_STORE_MSG_SELL);
        /* 98 */ RegisterPacket<RequestPetGetItemPacket>(IncomingPacketCodes.REQUEST_PET_GET_ITEM);
        // /* 99 */ RegisterPacket<RequestPrivateStoreManageBuyPacket>(IncomingPacketCodes.REQUEST_PRIVATE_STORE_MANAGE_BUY);
        // /* 9A */ RegisterPacket<SetPrivateStoreListBuyPacket>(IncomingPacketCodes.SET_PRIVATE_STORE_LIST_BUY);
        // /* 9C */ RegisterPacket<RequestPrivateStoreQuitBuyPacket>(IncomingPacketCodes.REQUEST_PRIVATE_STORE_QUIT_BUY);
        // /* 9D */ RegisterPacket<SetPrivateStoreMsgBuyPacket>(IncomingPacketCodes.SET_PRIVATE_STORE_MSG_BUY);
        // /* 9F */ RegisterPacket<RequestPrivateStoreSellPacket>(IncomingPacketCodes.REQUEST_PRIVATE_STORE_SELL);
        /* A6 */ RegisterPacket<RequestSkillCoolTimePacket>(IncomingPacketCodes.REQUEST_SKILL_COOL_TIME).WithAllowedStates(GameSessionState.EnteringGame | GameSessionState.InGame);;
        // /* A7 */ RegisterPacket<RequestPackageSendableItemListPacket>(IncomingPacketCodes.REQUEST_PACKAGE_SENDABLE_ITEM_LIST);
        // /* A8 */ RegisterPacket<RequestPackageSendPacket>(IncomingPacketCodes.REQUEST_PACKAGE_SEND);
        // /* A9 */ RegisterPacket<RequestBlockPacket>(IncomingPacketCodes.REQUEST_BLOCK);
        // /* AA */ RegisterPacket<RequestSiegeInfoPacket>(IncomingPacketCodes.REQUEST_SIEGE_INFO);
        // /* AB */ RegisterPacket<RequestSiegeAttackerListPacket>(IncomingPacketCodes.REQUEST_SIEGE_ATTACKER_LIST);
        // /* AC */ RegisterPacket<RequestSiegeDefenderListPacket>(IncomingPacketCodes.REQUEST_SIEGE_DEFENDER_LIST);
        // /* AD */ RegisterPacket<RequestJoinSiegePacket>(IncomingPacketCodes.REQUEST_JOIN_SIEGE);
        // /* AE */ RegisterPacket<RequestConfirmSiegeWaitingListPacket>(IncomingPacketCodes.REQUEST_CONFIRM_SIEGE_WAITING_LIST);
        // /* AF */ RegisterPacket<RequestSetCastleSiegeTimePacket>(IncomingPacketCodes.REQUEST_SET_CASTLE_SIEGE_TIME);
        // /* B0 */ RegisterPacket<MultiSellChoosePacket>(IncomingPacketCodes.MULTI_SELL_CHOOSE);
	    /* B3 */ RegisterPacket<BypassUserCmdPacket>(IncomingPacketCodes.BYPASS_USER_CMD);
		// /* B4 */ RegisterPacket<SnoopQuitPacket>(IncomingPacketCodes.SNOOP_QUIT);
		// /* B5 */ RegisterPacket<RequestRecipeBookOpenPacket>(IncomingPacketCodes.REQUEST_RECIPE_BOOK_OPEN);
		// /* B6 */ RegisterPacket<RequestRecipeBookDestroyPacket>(IncomingPacketCodes.REQUEST_RECIPE_BOOK_DESTROY);
		// /* B7 */ RegisterPacket<RequestRecipeItemMakeInfoPacket>(IncomingPacketCodes.REQUEST_RECIPE_ITEM_MAKE_INFO);
		// /* B8 */ RegisterPacket<RequestRecipeItemMakeSelfPacket>(IncomingPacketCodes.REQUEST_RECIPE_ITEM_MAKE_SELF);
		// /* BA */ RegisterPacket<RequestRecipeShopMessageSetPacket>(IncomingPacketCodes.REQUEST_RECIPE_SHOP_MESSAGE_SET);
		// /* BB */ RegisterPacket<RequestRecipeShopListSetPacket>(IncomingPacketCodes.REQUEST_RECIPE_SHOP_LIST_SET);
		// /* BC */ RegisterPacket<RequestRecipeShopManageQuitPacket>(IncomingPacketCodes.REQUEST_RECIPE_SHOP_MANAGE_QUIT);
		// /* BE */ RegisterPacket<RequestRecipeShopMakeInfoPacket>(IncomingPacketCodes.REQUEST_RECIPE_SHOP_MAKE_INFO);
		// /* BF */ RegisterPacket<RequestRecipeShopMakeItemPacket>(IncomingPacketCodes.REQUEST_RECIPE_SHOP_MAKE_ITEM);
		// /* C0 */ RegisterPacket<RequestRecipeShopManagePrevPacket>(IncomingPacketCodes.REQUEST_RECIPE_SHOP_MANAGE_PREV);
		// /* C1 */ RegisterPacket<ObserverReturnPacket>(IncomingPacketCodes.OBSERVER_RETURN);
		// /* C3 */ RegisterPacket<RequestHennaItemListPacket>(IncomingPacketCodes.REQUEST_HENNA_ITEM_LIST);
		// /* C4 */ RegisterPacket<RequestHennaItemInfoPacket>(IncomingPacketCodes.REQUEST_HENNA_ITEM_INFO);
		// /* C5 */ RegisterPacket<RequestBuySeedPacket>(IncomingPacketCodes.REQUEST_BUY_SEED);
		// /* C6 */ RegisterPacket<DlgAnswerPacket>(IncomingPacketCodes.DLG_ANSWER);
		// /* C7 */ RegisterPacket<RequestPreviewItemPacket>(IncomingPacketCodes.REQUEST_PREVIEW_ITEM);
		// /* C9 */ RegisterPacket<RequestPetitionFeedbackPacket>(IncomingPacketCodes.REQUEST_PETITION_FEEDBACK);
		/* CB */ RegisterPacket<GameGuardReplyPacket>(IncomingPacketCodes.GAME_GUARD_REPLY);
		// /* CC */ RegisterPacket<RequestPledgePowerPacket>(IncomingPacketCodes.REQUEST_PLEDGE_POWER);
		// /* CD */ RegisterPacket<RequestMakeMacroPacket>(IncomingPacketCodes.REQUEST_MAKE_MACRO);
		// /* CE */ RegisterPacket<RequestDeleteMacroPacket>(IncomingPacketCodes.REQUEST_DELETE_MACRO);

        /* D0:0001 */ RegisterPacket<RequestManorListPacket>(IncomingPacketCodes.REQUEST_MANOR_LIST).WithAllowedStates(GameSessionState.EnteringGame | GameSessionState.InGame);
		// /* D0:0002 */ RegisterPacket<RequestProcureCropListPacket>(IncomingPacketCodes.REQUEST_PROCEDURE_CROP_LIST);
		// /* D0:0003 */ RegisterPacket<RequestSetSeedPacket>(IncomingPacketCodes.REQUEST_SET_SEED);
		// /* D0:0004 */ RegisterPacket<RequestSetCropPacket>(IncomingPacketCodes.REQUEST_SET_CROP);
		// /* D0:0005 */ RegisterPacket<RequestWriteHeroWordsPacket>(IncomingPacketCodes.REQUEST_WRITE_HERO_WORDS);
		// /* D0:0006 */ RegisterPacket<RequestExAskJoinMPCCPacket>(IncomingPacketCodes.REQUEST_EX_ASK_JOIN_MPCC);
		// /* D0:0007 */ RegisterPacket<RequestExAcceptJoinMPCCPacket>(IncomingPacketCodes.REQUEST_EX_ACCEPT_JOIN_MPCC);
		// /* D0:0008 */ RegisterPacket<RequestExOustFromMPCCPacket>(IncomingPacketCodes.REQUEST_EX_OUST_FROM_MPCC);
		// /* D0:0009 */ RegisterPacket<RequestOustFromPartyRoomPacket>(IncomingPacketCodes.REQUEST_OUST_FROM_PARTY_ROOM);
		// /* D0:000A */ RegisterPacket<RequestDismissPartyRoomPacket>(IncomingPacketCodes.REQUEST_DISMISS_PARTY_ROOM);
		// /* D0:000B */ RegisterPacket<RequestWithdrawPartyRoomPacket>(IncomingPacketCodes.REQUEST_WITHDRAW_PARTY_ROOM);
		// /* D0:000C */ RegisterPacket<RequestChangePartyLeaderPacket>(IncomingPacketCodes.REQUEST_CHANGE_PARTY_LEADER);
		// /* D0:000D */ RegisterPacket<RequestAutoSoulShotPacket>(IncomingPacketCodes.REQUEST_AUTO_SOULSHOT);
		// /* D0:000E */ RegisterPacket<RequestExEnchantSkillInfoPacket>(IncomingPacketCodes.REQUEST_EX_ENCHANT_SKILL_INFO);
		// /* D0:000F */ RegisterPacket<RequestExEnchantSkillPacket>(IncomingPacketCodes.REQUEST_EX_ENCHANT_SKILL);
		// /* D0:0010 */ RegisterPacket<RequestExPledgeCrestLargePacket>(IncomingPacketCodes.REQUEST_EX_PLEDGE_CREST_LARGE);
		// /* D0:0011 */ RegisterPacket<RequestExSetPledgeCrestLargePacket>(IncomingPacketCodes.REQUEST_EX_SET_PLEDGE_CREST_LARGE);
		// /* D0:0012 */ RegisterPacket<RequestPledgeSetAcademyMasterPacket>(IncomingPacketCodes.REQUEST_PLEDGE_SET_ACADEMY_MASTER);
		// /* D0:0013 */ RegisterPacket<RequestPledgePowerGradeListPacket>(IncomingPacketCodes.REQUEST_PLEDGE_POWER_GRADE_LIST);
		// /* D0:0014 */ RegisterPacket<RequestPledgeMemberPowerInfoPacket>(IncomingPacketCodes.REQUEST_PLEDGE_MEMBER_POWER_INFO);
		// /* D0:0015 */ RegisterPacket<RequestPledgeSetMemberPowerGradePacket>(IncomingPacketCodes.REQUEST_PLEDGE_SET_MEMBER_POWER_GRADE);
		// /* D0:0016 */ RegisterPacket<RequestPledgeMemberInfoPacket>(IncomingPacketCodes.REQUEST_PLEDGE_MEMBER_INFO);
		// /* D0:0017 */ RegisterPacket<RequestPledgeWarListPacket>(IncomingPacketCodes.REQUEST_PLEDGE_WAR_LIST);
		// /* D0:0018 */ RegisterPacket<RequestExFishRankingPacket>(IncomingPacketCodes.REQUEST_EX_FISH_RANKING);
		// /* D0:0019 */ RegisterPacket<RequestPCCafeCouponUsePacket>(IncomingPacketCodes.REQUEST_PCCAFE_COUPON_USE);
		// /* D0:001B */ RegisterPacket<RequestDuelStartPacket>(IncomingPacketCodes.REQUEST_DUEL_START);
		// /* D0:001C */ RegisterPacket<RequestDuelAnswerStartPacket>(IncomingPacketCodes.REQUEST_DUAL_ANSWER_START);
		// /* D0:001E */ RegisterPacket<RequestExRqItemLinkPacket>(IncomingPacketCodes.REQUEST_EX_RQ_ITEM_LINK);
		// /* D0:0020 */ RegisterPacket<MoveToLocationInAirShipPacket>(IncomingPacketCodes.MOVE_TO_LOCATION_IN_AIR_SHIP);
        /* D0:0021 */ RegisterPacket<RequestKeyMappingPacket>(IncomingPacketCodes.REQUEST_KEY_MAPPING).WithAllowedStates(GameSessionState.EnteringGame | GameSessionState.InGame);
        // /* D0:0022 */ RegisterPacket<RequestSaveKeyMappingPacket>(IncomingPacketCodes.REQUEST_SAVE_KEY_MAPPING);
        // /* D0:0023 */ RegisterPacket<RequestExRemoveItemAttributePacket>(IncomingPacketCodes.REQUEST_EX_REMOVE_ITEM_ATTRIBUTE);
        /* D0:0024 */ RegisterPacket<RequestSaveInventoryOrderPacket>(IncomingPacketCodes.REQUEST_SAVE_INVENTORY_ORDER);
        // /* D0:0025 */ RegisterPacket<RequestExitPartyMatchingWaitingRoomPacket>(IncomingPacketCodes.REQUEST_EXIT_PARTY_MATCHING_WAITING_ROOM);
        // /* D0:0026 */ RegisterPacket<RequestConfirmTargetItemPacket>(IncomingPacketCodes.REQUEST_CONFIRM_TARGET_ITEM);
        // /* D0:0027 */ RegisterPacket<RequestConfirmRefinerItemPacket>(IncomingPacketCodes.REQUEST_CONFIRM_REFINER_ITEM);
        // /* D0:0028 */ RegisterPacket<RequestConfirmGemStonePacket>(IncomingPacketCodes.REQUEST_CONFIRM_GEMSTONE);
        // /* D0:0029 */ RegisterPacket<RequestOlympiadObserverEndPacket>(IncomingPacketCodes.REQUEST_OLYMPIAD_OBSERVER_END);
        // /* D0:002A */ RegisterPacket<RequestCursedWeaponListPacket>(IncomingPacketCodes.REQUEST_CURSED_WEAPON_LIST);
        // /* D0:002B */ RegisterPacket<RequestCursedWeaponLocationPacket>(IncomingPacketCodes.REQUEST_CURSED_WEAPON_LOCATION);
        // /* D0:002C */ RegisterPacket<RequestPledgeReorganizeMemberPacket>(IncomingPacketCodes.REQUEST_PLEDGE_REORGANIZE_MEMBER);
        // /* D0:002D */ RegisterPacket<RequestExMPCCShowPartyMembersInfoPacket>(IncomingPacketCodes.REQUEST_EX_MPCC_SHOW_PARTY_MEMBERS_INFO);
        // /* D0:002E */ RegisterPacket<RequestOlympiadMatchListPacket>(IncomingPacketCodes.REQUEST_OLYMPIAD_MATCH_LIST);
        // /* D0:002F */ RegisterPacket<RequestAskJoinPartyRoomPacket>(IncomingPacketCodes.REQUEST_ASK_JOIN_PARTY_ROOM);
        // /* D0:0030 */ RegisterPacket<AnswerJoinPartyRoomPacket>(IncomingPacketCodes.ANSWER_JOIN_PARTY_ROOM);
        // /* D0:0031 */ RegisterPacket<RequestListPartyMatchingWaitingRoomPacket>(IncomingPacketCodes.REQUEST_LIST_PARTY_MATCHING_WAITING_ROOM);
        // /* D0:0032 */ RegisterPacket<RequestExEnchantItemAttributePacket>(IncomingPacketCodes.REQUEST_EX_ENCHANT_ITEM_ATTRIBUTE);
        /* D0:0033 */ RegisterPacket<RequestGoToLobbyPacket>(IncomingPacketCodes.REQUEST_GOTO_LOBBY).WithAllowedStates(GameSessionState.CharacterScreen);
        // /* D0:0035 */ RegisterPacket<MoveToLocationAirShipPacket>(IncomingPacketCodes.MOVE_TO_LOCATION_AIR_SHIP);
        // /* D0:0036 */ RegisterPacket<RequestBidItemAuctionPacket>(IncomingPacketCodes.REQUEST_BID_ITEM_AUCTION);
        // /* D0:0037 */ RegisterPacket<RequestInfoItemAuctionPacket>(IncomingPacketCodes.REQUEST_INFO_ITEM_AUCTION);
        // /* D0:0038 */ RegisterPacket<RequestExChangeNamePacket>(IncomingPacketCodes.REQUEST_EX_CHANGE_NAME);
        /* D0:0039 */ RegisterPacket<RequestAllCastleInfoPacket>(IncomingPacketCodes.REQUEST_ALL_CASTLE_INFO);
        /* D0:003A */ RegisterPacket<RequestAllFortressInfoPacket>(IncomingPacketCodes.REQUEST_ALL_FORTRESS_INFO);
        // /* D0:003B */ RegisterPacket<RequestAllAgitInfoPacket>(IncomingPacketCodes.REQUEST_ALL_AGIT_INGO);
        // /* D0:003C */ RegisterPacket<RequestFortressSiegeInfoPacket>(IncomingPacketCodes.REQUEST_FORTRESS_SIEGE_INFO);
        // /* D0:003D */ RegisterPacket<RequestGetBossRecordPacket>(IncomingPacketCodes.REQUEST_GET_BOSS_RECORD);
        // /* D0:003E */ RegisterPacket<RequestRefinePacket>(IncomingPacketCodes.REQUEST_REFINE);
        // /* D0:003F */ RegisterPacket<RequestConfirmCancelItemPacket>(IncomingPacketCodes.REQUEST_CONFIRM_CANCEL_ITEM);
        // /* D0:0040 */ RegisterPacket<RequestRefineCancelPacket>(IncomingPacketCodes.REQUEST_REFINE_CANCEL);
        // /* D0:0041 */ RegisterPacket<RequestExMagicSkillUseGroundPacket>(IncomingPacketCodes.REQUEST_EX_MAGIC_SKILL_USE_GROUND);
        // /* D0:0042 */ RegisterPacket<RequestDuelSurrenderPacket>(IncomingPacketCodes.REQUEST_DUEL_SURRENDER);
        // /* D0:0043 */ RegisterPacket<RequestExEnchantSkillInfoDetailPacket>(IncomingPacketCodes.REQUEST_EX_ENCHANT_SKILL_INFO_DETAIL);
        // /* D0:0045 */ RegisterPacket<RequestFortressMapInfoPacket>(IncomingPacketCodes.REQUEST_FORTRESS_MAP_INFO);
        // /* D0:0046 */ RegisterPacket<RequestPVPMatchRecordPacket>(IncomingPacketCodes.REQUEST_PVP_MATCH_RECORD);
        // /* D0:0047 */ RegisterPacket<SetPrivateStoreWholeMsgPacket>(IncomingPacketCodes.SET_PRIVATE_STORE_WHOLE_MSG);
        /* D0:0048 */ RegisterPacket<RequestDispelPacket>(IncomingPacketCodes.REQUEST_DISPEL);
		// /* D0:0049 */ RegisterPacket<RequestExTryToPutEnchantTargetItemPacket>(IncomingPacketCodes.REQUEST_EX_TRY_TO_PUT_ENCHANT_TARGET_ITEM);
		// /* D0:004A */ RegisterPacket<RequestExTryToPutEnchantSupportItemPacket>(IncomingPacketCodes.REQUEST_EX_TRY_TO_PUT_ENCHANT_SUPPORT_ITEM);
		// /* D0:004B */ RegisterPacket<RequestExCancelEnchantItemPacket>(IncomingPacketCodes.REQUEST_EX_CANCEL_ENCHANT_ITEM);
		// /* D0:004C */ RegisterPacket<RequestChangeNicknameColorPacket>(IncomingPacketCodes.REQUEST_CHANGE_NICKNAME_COLOR);
		// /* D0:004D */ RegisterPacket<RequestResetNicknamePacket>(IncomingPacketCodes.REQUEST_RESET_NICKNAME);
		// /* D0:004E */ RegisterPacket<ExBookmarkPacketPacket>(IncomingPacketCodes.EX_BOOKMARK_PACKET);
		// /* D0:004F */ RegisterPacket<RequestWithDrawPremiumItemPacket>(IncomingPacketCodes.REQUEST_WITHDRAW_PREMIUM_ITEM);
		// /* D0:0058 */ RegisterPacket<EndScenePlayerPacket>(IncomingPacketCodes.END_SCENE_PLAYER);
		// /* D0:005A */ RegisterPacket<RequestExListMpccWaitingPacket>(IncomingPacketCodes.REQUEST_EX_LIST_MPCC_WAITING);
		// /* D0:005B */ RegisterPacket<RequestExManageMpccRoomPacket>(IncomingPacketCodes.REQUEST_EX_MANAGE_MPCC_ROOM);
		// /* D0:005C */ RegisterPacket<RequestExJoinMpccRoomPacket>(IncomingPacketCodes.REQUEST_EX_JOIN_MPCC_ROOM);
		// /* D0:005D */ RegisterPacket<RequestExOustFromMpccRoomPacket>(IncomingPacketCodes.REQUEST_EX_OUST_FROM_MPCC_ROOM);
		// /* D0:005E */ RegisterPacket<RequestExDismissMpccRoomPacket>(IncomingPacketCodes.REQUEST_EX_DISMISS_MPCC_ROOM);
		// /* D0:005F */ RegisterPacket<RequestExWithdrawMpccRoomPacket>(IncomingPacketCodes.REQUEST_EX_WITHDRAW_MPCC_ROOM);
		// /* D0:0060 */ RegisterPacket<RequestSeedPhasePacket>(IncomingPacketCodes.REQUEST_SEED_PHASE);
		// /* D0:0061 */ RegisterPacket<RequestExMpccPartymasterListPacket>(IncomingPacketCodes.REQUEST_EX_MPCC_PARTYMASTER_LIST);
		// /* D0:0062 */ RegisterPacket<RequestPostItemListPacket>(IncomingPacketCodes.REQUEST_POST_ITEM_LIST);
		// /* D0:0063 */ RegisterPacket<RequestSendPostPacket>(IncomingPacketCodes.REQUEST_SEND_POST);
        /* D0:0064 */ RegisterPacket<RequestReceivedPostListPacket>(IncomingPacketCodes.REQUEST_RECEIVED_POST_LIST);
		// /* D0:0065 */ RegisterPacket<RequestDeleteReceivedPostPacket>(IncomingPacketCodes.REQUEST_DELETE_RECEIVED_POST);
		// /* D0:0066 */ RegisterPacket<RequestReceivedPostPacket>(IncomingPacketCodes.REQUEST_RECEIVED_POST);
		// /* D0:0067 */ RegisterPacket<RequestPostAttachmentPacket>(IncomingPacketCodes.REQUEST_POST_ATTACHMENT);
		// /* D0:0068 */ RegisterPacket<RequestRejectPostAttachmentPacket>(IncomingPacketCodes.REQUEST_REJECT_POST_ATTACHMENT);
		// /* D0:0069 */ RegisterPacket<RequestSentPostListPacket>(IncomingPacketCodes.REQUEST_SENT_POST_LIST);
		// /* D0:006A */ RegisterPacket<RequestDeleteSentPostPacket>(IncomingPacketCodes.REQUEST_DELETE_SENT_POST);
		// /* D0:006B */ RegisterPacket<RequestSentPostPacket>(IncomingPacketCodes.REQUEST_SENT_POST);
		// /* D0:006C */ RegisterPacket<RequestCancelPostAttachmentPacket>(IncomingPacketCodes.REQUEST_CANCEL_POST_ATTACHMENT);
		// /* D0:0072 */ RegisterPacket<RequestRefundItemPacket>(IncomingPacketCodes.REQUEST_REFUND_ITEM);
		// /* D0:0073 */ RegisterPacket<RequestBuySellUIClosePacket>(IncomingPacketCodes.REQUEST_BUI_SELL_UI_CLOSE);
		// /* D0:0075 */ RegisterPacket<RequestPartyLootModificationPacket>(IncomingPacketCodes.REQUEST_PARTY_LOOT_MODIFICATION);
		// /* D0:0076 */ RegisterPacket<AnswerPartyLootModificationPacket>(IncomingPacketCodes.ANSWER_PARTY_LOOT_MODIFICATION);
		// /* D0:0077 */ RegisterPacket<AnswerCoupleActionPacket>(IncomingPacketCodes.ANSWER_COUPLE_ACTION);
		// /* D0:0078 */ RegisterPacket<BrEventRankerListPacket>(IncomingPacketCodes.BR_EVENT_RANKER_LIST);
		// /* D0:007A */ RegisterPacket<RequestAddExpandQuestAlarmPacket>(IncomingPacketCodes.REQUEST_ADD_EXPAND_QUEST_ALARM);
		// /* D0:007B */ RegisterPacket<RequestVoteNewPacket>(IncomingPacketCodes.REQUEST_VOTE_NEW);
		// /* D0:007C */ RegisterPacket<RequestShuttleGetOnPacket>(IncomingPacketCodes.REQUEST_SHUTTLE_GET_ON);
		// /* D0:007D */ RegisterPacket<RequestShuttleGetOffPacket>(IncomingPacketCodes.REQUEST_SHUTTLE_GET_OFF);
		// /* D0:007E */ RegisterPacket<MoveToLocationInShuttlePacket>(IncomingPacketCodes.MOVE_TO_LOCATION_IN_SHUTTLE);
		// /* D0:007F */ RegisterPacket<CannotMoveAnymoreInShuttlePacket>(IncomingPacketCodes.CANNOT_MOVE_ANYMORE_IN_SHUTTLE);
		// /* D0:0081 */ RegisterPacket<RequestExAddContactToContactListPacket>(IncomingPacketCodes.REQUEST_EX_ADD_CONTACT_TO_CONTACT_LIST);
		// /* D0:0082 */ RegisterPacket<RequestExDeleteContactFromContactListPacket>(IncomingPacketCodes.REQUEST_EX_DELETE_CONTACT_FROM_CONTACT_LIST);
		// /* D0:0083 */ RegisterPacket<RequestExShowContactListPacket>(IncomingPacketCodes.REQUEST_EX_SHOW_CONTACT_LIST);
		// /* D0:0084 */ RegisterPacket<RequestExFriendListExtendedPacket>(IncomingPacketCodes.REQUEST_EX_FRIEND_LIST_EXTENDED);
		// /* D0:0085 */ RegisterPacket<RequestExOlympiadMatchListRefreshPacket>(IncomingPacketCodes.REQUEST_EX_OLYMPIAD_MATCH_LIST_REFRESH);
		// /* D0:0086 */ RegisterPacket<RequestBRGamePointPacket>(IncomingPacketCodes.REQUEST_BR_GAME_POINT);
		// /* D0:0087 */ RegisterPacket<RequestBRProductListPacket>(IncomingPacketCodes.REQUEST_BR_PRODUCT_LIST);
		// /* D0:0088 */ RegisterPacket<RequestBRProductInfoPacket>(IncomingPacketCodes.REQUEST_BR_PRODUCT_INFO);
		// /* D0:0089 */ RegisterPacket<RequestBRBuyProductPacket>(IncomingPacketCodes.REQUEST_BR_BUI_PRODUCT);
		// /* D0:008A */ RegisterPacket<RequestBRRecentProductListPacket>(IncomingPacketCodes.REQUEST_BR_RECENT_PRODUCT_LIST);
		// /* D0:008E */ RegisterPacket<RequestCrystallizeEstimatePacket>(IncomingPacketCodes.REQUEST_CRYSTALLIZE_ESTIMATE);
		// /* D0:008F */ RegisterPacket<RequestCrystallizeItemCancelPacket>(IncomingPacketCodes.REQUEST_CRYSTALLIZE_ITEM_CANCEL);
		// /* D0:0090 */ RegisterPacket<RequestExEscapeScenePacket>(IncomingPacketCodes.REQUEST_SCENE_EX_ESCAPE_SCENE);
		// /* D0:0091 */ RegisterPacket<RequestFlyMovePacket>(IncomingPacketCodes.REQUEST_FLY_MOVE);
		// /* D0:0094 */ RegisterPacket<RequestFriendDetailInfoPacket>(IncomingPacketCodes.REQUEST_FRIEND_DETAIL_INFO);
		// /* D0:0095 */ RegisterPacket<RequestUpdateFriendMemoPacket>(IncomingPacketCodes.REQUEST_UPDATE_FRIEND_MEMO);
		// /* D0:0096 */ RegisterPacket<RequestBlockMemoPacket>(IncomingPacketCodes.REQUEST_UPDATE_BLOCK_MEMO);
		// /* D0:0098 */ RegisterPacket<RequestCommissionRegistrableItemListPacket>(IncomingPacketCodes.REQUEST_COMMISSION_REGISTRABLE_ITEM_LIST);
		// /* D0:0099 */ RegisterPacket<RequestCommissionInfoPacket>(IncomingPacketCodes.REQUEST_COMMISSION_INFO);
		// /* D0:009A */ RegisterPacket<RequestCommissionRegisterPacket>(IncomingPacketCodes.REQUEST_COMMISSION_REGISTER);
		// /* D0:009B */ RegisterPacket<RequestCommissionCancelPacket>(IncomingPacketCodes.REQUEST_COMMISSION_CANCEL);
		// /* D0:009C */ RegisterPacket<RequestCommissionDeletePacket>(IncomingPacketCodes.REQUEST_COMMISSION_DELETE);
		// /* D0:009D */ RegisterPacket<RequestCommissionListPacket>(IncomingPacketCodes.REQUEST_COMMISSION_LIST);
		// /* D0:009E */ RegisterPacket<RequestCommissionBuyInfoPacket>(IncomingPacketCodes.REQUEST_COMMISSION_BUY_INFO);
		// /* D0:009F */ RegisterPacket<RequestCommissionBuyItemPacket>(IncomingPacketCodes.REQUEST_COMMISSION_BUY_ITEM);
		// /* D0:00A0 */ RegisterPacket<RequestCommissionRegisteredItemPacket>(IncomingPacketCodes.REQUEST_COMMISSION_REGISTERED_ITEM);
		// /* D0:00A2 */ RegisterPacket<RequestChangeToAwakenedClassPacket>(IncomingPacketCodes.REQUEST_CHANGE_TO_AWAKENED_CLASS);
		// /* D0:00A6 */ RegisterPacket<RequestEx2ndPasswordCheckPacket>(IncomingPacketCodes.REQUEST_EX_2ND_PASSWORD_CHECK).WithAllowedStates(GameSessionState.Authorization);
		// /* D0:00A7 */ RegisterPacket<RequestEx2ndPasswordVerifyPacket>(IncomingPacketCodes.REQUEST_EX_2ND_PASSWORD_VERIFY).WithAllowedStates(GameSessionState.Authorization);
		// /* D0:00A8 */ RegisterPacket<RequestEx2ndPasswordReqPacket>(IncomingPacketCodes.REQUEST_EX_2ND_PASSWORD_REQ).WithAllowedStates(GameSessionState.Authorization);
        /* D0:00A9 */ RegisterPacket<RequestCharacterNameCreatablePacket>(IncomingPacketCodes.REQUEST_CHARACTER_NAME_CREATABLE).WithAllowedStates(GameSessionState.CharacterScreen);
        // /* D0:00AD */ RegisterPacket<RequestFlyMoveStartPacket>(IncomingPacketCodes.REQUEST_FLY_MOVE_START);
        // /* D0:00AE */ RegisterPacket<RequestHardWareInfoPacket>(IncomingPacketCodes.REQUEST_HARDWARE_INFO).WithAllowedStates(GameSessionState.All);
        // /* D0:00B0 */ RegisterPacket<SendChangeAttributeTargetItemPacket>(IncomingPacketCodes.SEND_CHANGE_ATTRIBUTE_TARGET_ITEM);
        // /* D0:00B1 */ RegisterPacket<RequestChangeAttributeItemPacket>(IncomingPacketCodes.REQUEST_CHANGE_ATTRIBUTE_ITEM);
        // /* D0:00B2 */ RegisterPacket<RequestChangeAttributeCancelPacket>(IncomingPacketCodes.REQUEST_CHANGE_ATTRIBUTE_CANCEL);
        // /* D0:00B3 */ RegisterPacket<RequestBRPresentBuyProductPacket>(IncomingPacketCodes.REQUEST_BR_PRESENT_BUY_PRODUCT);
        // /* D0:00B4 */ RegisterPacket<ConfirmMenteeAddPacket>(IncomingPacketCodes.CONFIRM_MENTEE_ADD);
        // /* D0:00B5 */ RegisterPacket<RequestMentorCancelPacket>(IncomingPacketCodes.REQUEST_MENTOR_CANCEL);
        // /* D0:00B6 */ RegisterPacket<RequestMentorListPacket>(IncomingPacketCodes.REQUEST_MENTOR_LIST);
        // /* D0:00B7 */ RegisterPacket<RequestMenteeAddPacket>(IncomingPacketCodes.REQUEST_MENTEE_ADD);
        // /* D0:00B8 */ RegisterPacket<RequestMenteeWaitingListPacket>(IncomingPacketCodes.REQUEST_MENTEE_WAITING_LIST);
        /* D0:00B9 */ RegisterPacket<RequestClanAskJoinByNamePacket>(IncomingPacketCodes.REQUEST_CLAN_ASK_JOIN_BY_NAME);
		// /* D0:00BA */ RegisterPacket<RequestInzoneWaitingTimePacket>(IncomingPacketCodes.REQUEST_IN_ZONE_WAITING_TIME);
		// /* D0:00C4 */ RegisterPacket<RequestExTryToPutShapeShiftingTargetItemPacket>(IncomingPacketCodes.REQUEST_EX_TRY_TO_PUT_SHAPE_SHIFTING_TARGET_ITEM);
		// /* D0:00C5 */ RegisterPacket<RequestExTryToPutShapeShiftingEnchantSupportItemPacket>(IncomingPacketCodes.REQUEST_EX_TRY_TO_PUT_SHAPE_SHIFTING_ENCHANT_SUPPORT_ITEM);
		// /* D0:00C6 */ RegisterPacket<RequestExCancelShape_Shifting_ItemPacket>(IncomingPacketCodes.REQUEST_EX_CANCEL_SHAPE_SHIFTING_ITEM);
		// /* D0:00C7 */ RegisterPacket<RequestShapeShiftingItemPacket>(IncomingPacketCodes.REQUEST_SHAPE_SHIFTING_ITEM);
		// /* D0:00CA */ RegisterPacket<RequestShowBeautyListPacket>(IncomingPacketCodes.REQUEST_SHOW_BEAUTY_LIST);
		// /* D0:00CB */ RegisterPacket<RequestRegistBeautyPacket>(IncomingPacketCodes.REQUEST_REGIST_BEAUTY);
		// /* D0:00CD */ RegisterPacket<RequestShowResetShopListPacket>(IncomingPacketCodes.REQUEST_SHOW_RESET_SHOP_LIST);
		// /* D0:00D3 */ RegisterPacket<RequestPledgeRecruitInfoPacket>(IncomingPacketCodes.REQUEST_PLEDGE_RECRUIT_INFO);
		// /* D0:00D4 */ RegisterPacket<RequestPledgeRecruitBoardSearchPacket>(IncomingPacketCodes.REQUEST_PLEDGE_RECRUIT_BOARD_SEARCH);
		// /* D0:00D5 */ RegisterPacket<RequestPledgeRecruitBoardAccessPacket>(IncomingPacketCodes.REQUEST_PLEDGE_RECRUIT_BOARD_ACCESS);
		// /* D0:00D6 */ RegisterPacket<RequestPledgeRecruitBoardDetailPacket>(IncomingPacketCodes.REQUEST_PLEDGE_RECRUIT_BOARD_DETAIL);
		// /* D0:00D7 */ RegisterPacket<RequestPledgeWaitingApplyPacket>(IncomingPacketCodes.REQUEST_PLEDGE_WAITING_APPLY);
		// /* D0:00D8 */ RegisterPacket<RequestPledgeWaitingAppliedPacket>(IncomingPacketCodes.REQUEST_PLEDGE_WAITING_APPLIED);
		// /* D0:00D9 */ RegisterPacket<RequestPledgeWaitingListPacket>(IncomingPacketCodes.REQUEST_PLEDGE_WAITING_LIST);
		// /* D0:00DA */ RegisterPacket<RequestPledgeWaitingUserPacket>(IncomingPacketCodes.REQUEST_PLEDGE_WAITING_USER);
		// /* D0:00DB */ RegisterPacket<RequestPledgeWaitingUserAcceptPacket>(IncomingPacketCodes.REQUEST_PLEDGE_WAITING_USER_ACCEPT);
		// /* D0:00DC */ RegisterPacket<RequestPledgeDraftListSearchPacket>(IncomingPacketCodes.REQUEST_PLEDGE_DRAFT_LIST_SEARCH);
		// /* D0:00DD */ RegisterPacket<RequestPledgeDraftListApplyPacket>(IncomingPacketCodes.REQUEST_PLEDGE_DRAFT_LIST_APPLY);
		// /* D0:00DE */ RegisterPacket<RequestPledgeRecruitApplyInfoPacket>(IncomingPacketCodes.REQUEST_PLEDGE_RECRUIT_APPLY_INFO);
		// /* D0:00E1 */ RegisterPacket<NotifyExitBeautyShopPacket>(IncomingPacketCodes.NOTIFY_EXIT_BEAUTY_SHOP);
		// /* D0:00E3 */ RegisterPacket<RequestExAddEnchantScrollItemPacket>(IncomingPacketCodes.REQUEST_EX_ADD_ENCHANT_SCROLL_ITEM);
		// /* D0:00E4 */ RegisterPacket<RequestExRemoveEnchantSupportItemPacket>(IncomingPacketCodes.REQUEST_EX_REMOVE_ENCHANT_SUPPORT_ITEM);
		// /* D0:00E6 */ RegisterPacket<RequestDivideAdenaStartPacket>(IncomingPacketCodes.REQUEST_DIVIDE_ADENA_START);
		// /* D0:00E7 */ RegisterPacket<RequestDivideAdenaCancelPacket>(IncomingPacketCodes.REQUEST_DIVIDE_ADENA_CANCEL);
		// /* D0:00E8 */ RegisterPacket<RequestDivideAdenaPacket>(IncomingPacketCodes.REQUEST_DIVIDE_ADENA);
		// /* D0:00ED */ RegisterPacket<RequestStopMovePacket>(IncomingPacketCodes.REQUEST_STOP_MOVE);
		// /* D0:00F0 */ RegisterPacket<RequestLuckyGameStartInfoPacket>(IncomingPacketCodes.REQUEST_LUCKY_GAME_START_INFO);
		// /* D0:00F1 */ RegisterPacket<RequestLuckyGamePlayPacket>(IncomingPacketCodes.REQUEST_LUCKY_GAME_PLAY);
		// /* D0:00F2 */ RegisterPacket<NotifyTrainingRoomEndPacket>(IncomingPacketCodes.NOTIFY_TRAINING_ROOM_END);
		// /* D0:00F3 */ RegisterPacket<RequestNewEnchantPushOnePacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_PUSH_ONE);
		// /* D0:00F4 */ RegisterPacket<RequestNewEnchantRemoveOnePacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_REMOVE_ONE);
		// /* D0:00F5 */ RegisterPacket<RequestNewEnchantPushTwoPacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_PUSH_TWO);
		// /* D0:00F6 */ RegisterPacket<RequestNewEnchantRemoveTwoPacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_REMOVE_TWO);
		// /* D0:00F7 */ RegisterPacket<RequestNewEnchantClosePacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_CLOSE);
		// /* D0:00F8 */ RegisterPacket<RequestNewEnchantTryPacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_TRY);
		// /* D0:00F9 */ RegisterPacket<RequestNewEnchantRetryToPutItemsPacket>(IncomingPacketCodes.REQUEST_NEW_ENCHANT_RETRY_TO_PUT_ITEMS);
        /* D0:00FD */ RegisterPacket<RequestTargetActionMenuPacket>(IncomingPacketCodes.REQUEST_TARGET_ACTION_MENU);
		// /* D0:00FE */ RegisterPacket<ExSendSelectedQuestZoneIDPacket>(IncomingPacketCodes.EX_SEND_SELECTED_QUEST_ZONE_ID);
		// /* D0:00FF */ RegisterPacket<RequestAlchemySkillListPacket>(IncomingPacketCodes.REQUEST_ALCHEMY_SKILL_LIST);
		// /* D0:0104 */ RegisterPacket<ExRequestAutoFishPacket>(IncomingPacketCodes.REQUEST_EX_AUTO_FISH);
		// /* D0:0105 */ RegisterPacket<RequestVipAttendanceItemListPacket>(IncomingPacketCodes.REQUEST_VIP_ATTENDANCE_ITEM_LIST);
		// /* D0:0106 */ RegisterPacket<RequestVipAttendanceCheckPacket>(IncomingPacketCodes.REQUEST_VIP_ATTENDANCE_CHECK);
		// /* D0:0107 */ RegisterPacket<RequestItemEnsoulPacket>(IncomingPacketCodes.REQUEST_ITEM_ENSOUL);
		// /* D0:010A */ RegisterPacket<RequestVipLuckGameInfoPacket>(IncomingPacketCodes.REQUEST_VIP_LUCKY_GAME_INFO);
		// /* D0:010D */ RegisterPacket<ExRequestVipInfoPacket>(IncomingPacketCodes.EX_REQUEST_VIP_INFO);
		// /* D0:0110 */ RegisterPacket<RequestPledgeSignInForOpenJoiningMethodPacket>(IncomingPacketCodes.REQUEST_PLEDGE_SIGN_IN_FOR_OPEN_JOINING_METHOD);
		// /* D0:011B */ RegisterPacket<RequestPartyMatchingHistoryPacket>(IncomingPacketCodes.REQUEST_PARTY_MATCHING_HISTORY);
        /* D0:011D */ RegisterPacket<RequestToDoListPacket>(IncomingPacketCodes.REQUEST_TODO_LIST);
        /* D0:011F */ RegisterPacket<RequestOneDayRewardReceivePacket>(IncomingPacketCodes.REQUEST_ONE_DAY_REWARD_RECEIVE);
		// /* D0:0121 */ RegisterPacket<RequestPledgeBonusOpenPacket>(IncomingPacketCodes.REQUEST_PLEDGE_BONUS_OPEN);
		// /* D0:0122 */ RegisterPacket<RequestPledgeBonusRewardListPacket>(IncomingPacketCodes.REQUEST_PLEDGE_BONUS_REWARD_LIST);
		// /* D0:0123 */ RegisterPacket<RequestPledgeBonusRewardPacket>(IncomingPacketCodes.REQUEST_PLEDGE_BONUS_REWARD);
		// /* D0:0126 */ RegisterPacket<RequestBlockDetailInfoPacket>(IncomingPacketCodes.REQUEST_BLOCK_MEMO_INFO);
		// /* D0:0127 */ RegisterPacket<RequestTryEnSoulExtractionPacket>(IncomingPacketCodes.REQUEST_TRY_EN_SOUL_EXTRACTION);
		// /* D0:0128 */ RegisterPacket<RequestRaidBossSpawnInfoPacket>(IncomingPacketCodes.REQUEST_RAIDBOSS_SPAWN_INFO);
		// /* D0:0129 */ RegisterPacket<RequestRaidServerInfoPacket>(IncomingPacketCodes.REQUEST_RAID_SERVER_INFO);
		// /* D0:0135 */ RegisterPacket<RequestUpgradeSystemResultPacket>(IncomingPacketCodes.REQUEST_UPGRADE_SYSTEM_RESULT);
		// /* D0:014F */ RegisterPacket<ExElementalSpiritInfoPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_INFO);
		// /* D0:0150 */ RegisterPacket<ExElementalSpiritExtractInfoPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_EXTRACT_INFO);
		// /* D0:0151 */ RegisterPacket<ExElementalSpiritExtractPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_EXTRACT);
		// /* D0:0152 */ RegisterPacket<ExElementalSpiritEvolutionInfoPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_EVOLUTION_INFO);
		// /* D0:0153 */ RegisterPacket<ExElementalSpiritEvolutionPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_EVOLUTION);
		// /* D0:0154 */ RegisterPacket<ExElementalSpiritSetTalentPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_SET_TALENT);
		// /* D0:0155 */ RegisterPacket<ExElementalInitTalentPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_INIT_TALENT);
		// /* D0:0156 */ RegisterPacket<ExElementalSpiritAbsorbInfoPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_ABSORB_INFO);
		// /* D0:0157 */ RegisterPacket<ExElementalSpiritAbsorbPacket>(IncomingPacketCodes.EX_ELEMENTAL_SPIRIT_ABSORB);
		// 152
		// /* D0:015E */ RegisterPacket<ExInteractModifyPacket>(IncomingPacketCodes.EX_INTERACT_MODIFY);
		// /* D0:0160 */ RegisterPacket<ExUpgradeSystemNormalRequestPacket>(IncomingPacketCodes.EX_UPGRADE_SYSTEM_NORMAL_REQUEST);
        /* D0:0161 */ RegisterPacket<RequestPurchaseLimitShopItemListPacket>(IncomingPacketCodes.EX_PURCHASE_LIMIT_SHOP_ITEM_LIST);
        // /* D0:0162 */ RegisterPacket<RequestPurchaseLimitShopItemBuyPacket>(IncomingPacketCodes.EX_PURCHASE_LIMIT_SHOP_ITEM_BUY);
        // 228
        /* D0:0163 */ RegisterPacket<ExOpenHtmlPacket>(IncomingPacketCodes.EX_OPEN_HTML);
        /* D0:0164 */ RegisterPacket<ExRequestClassChangePacket>(IncomingPacketCodes.EX_REQUEST_CLASS_CHANGE);
        /* D0:0165 */ RegisterPacket<ExRequestChangeClassVerifyingPacket>(IncomingPacketCodes.EX_REQUEST_CLASS_CHANGE_VERIFYING);
        /* D0:0166 */ RegisterPacket<ExRequestTeleportPacket>(IncomingPacketCodes.EX_REQUEST_TELEPORT);
        // /* D0:016E */ RegisterPacket<ExMagicLampGameInfoPacket>(IncomingPacketCodes.EX_MAGICLAMP_GAME_INFO);
        // /* D0:016F */ RegisterPacket<ExMagicLampGameStartPacket>(IncomingPacketCodes.EX_MAGICLAMP_GAME_START);
        /* D0:0170 */ RegisterPacket<ExRequestActivateAutoShortcutPacket>(IncomingPacketCodes.EX_ACTIVATE_AUTO_SHORTCUT);
        /* D0:0176 */ RegisterPacket<ExAutoPlaySettingsPacket>(IncomingPacketCodes.EX_AUTOPLAY_SETTING);
        /* D0:017E */ RegisterPacket<ExTimedHuntingZoneListPacket>(IncomingPacketCodes.EX_TIME_RESTRICT_FIELD_LIST);
        /* D0:017F */ RegisterPacket<ExTimedHuntingZoneEnterPacket>(IncomingPacketCodes.EX_TIME_RESTRICT_FIELD_USER_ENTER);
        /* D0:0180 */ RegisterPacket<ExTimedHuntingZoneLeavePacket>(IncomingPacketCodes.EX_TIME_RESTRICT_FIELD_USER_LEAVE);
        /* D0:0181 */ RegisterPacket<RequestRankingCharInfoPacket>(IncomingPacketCodes.EX_RANKING_CHAR_INFO);
        /* D0:0182 */ RegisterPacket<RequestRankingCharHistoryPacket>(IncomingPacketCodes.EX_RANKING_CHAR_HISTORY);
        /* D0:0183 */ RegisterPacket<RequestRankingCharRankersPacket>(IncomingPacketCodes.EX_RANKING_CHAR_RANKERS);
        // /* D0:0184 */ RegisterPacket<RequestExRankingCharSpawnBuffzoneNpcPacket>(IncomingPacketCodes.EX_RANKING_CHAR_SPAWN_BUFFZONE_NPC);
        // /* D0:0185 */ RegisterPacket<RequestExRankingCharBuffzoneNpcPositionPacket>(IncomingPacketCodes.EX_RANKING_CHAR_BUFFZONE_NPC_POSITION);
        /* D0:0187 */ RegisterPacket<ExMercenaryCastleWarCastleSiegeInfoPacket>(IncomingPacketCodes.EX_MERCENARY_CASTLEWAR_CASTLE_INFO);
        /* D0:0188 */ RegisterPacket<ExMercenaryCastleWarCastleSiegeInfoPacket>(IncomingPacketCodes.EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_INFO);
        // /* D0:0189 */ RegisterPacket<ExMercenaryCastleWarCastleSiegeAttackerListPacket>(IncomingPacketCodes.EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_ATTACKER_LIST);
        // /* D0:018A */ RegisterPacket<ExMercenaryCastleWarCastleSiegeDefenderListPacket>(IncomingPacketCodes.EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_DEFENDER_LIST);
        // /* D0:018D */ RegisterPacket<ExPvpBookListPacket>(IncomingPacketCodes.EX_PVP_BOOK_LIST);
        // /* D0:0190 */ RegisterPacket<ExLetterCollectorTakeRewardPacket>(IncomingPacketCodes.EX_LETTER_COLLECTOR_TAKE_REWARD);
        // /* D0:0191 */ RegisterPacket<ExSetStatusBonusPacket>(IncomingPacketCodes.EX_SET_STATUS_BONUS);
        // /* D0:0192 */ RegisterPacket<ExResetStatusBonusPacket>(IncomingPacketCodes.EX_RESET_STATUS_BONUS);
        // /* D0:0193 */ RegisterPacket<RequestOlympiadMyRankingInfoPacket>(IncomingPacketCodes.EX_OLYMPIAD_MY_RANKING_INFO);
        // /* D0:0194 */ RegisterPacket<RequestOlympiadRankingInfoPacket>(IncomingPacketCodes.EX_OLYMPIAD_RANKING_INFO);
        // /* D0:0195 */ RegisterPacket<RequestOlympiadHeroAndLegendInfoPacket>(IncomingPacketCodes.EX_OLYMPIAD_HERO_AND_LEGEND_INFO);
        // /* D0:0196 */ RegisterPacket<ExCastleWarObserverStartPacket>(IncomingPacketCodes.EX_CASTLEWAR_OBSERVER_START);
        /* D0:0197 */ RegisterPacket<RequestRaidTeleportInfoPacket>(IncomingPacketCodes.EX_RAID_TELEPORT_INFO);
        // /* D0:0198 */ RegisterPacket<ExTeleportToRaidPositionPacket>(IncomingPacketCodes.EX_TELEPORT_TO_RAID_POSITION);
        // /* D0:0199 */ RegisterPacket<ExRequestRandomCraftExtractPacket>(IncomingPacketCodes.EX_CRAFT_EXTRACT);
        // /* D0:019A */ RegisterPacket<ExRequestRandomCraftInfoPacket>(IncomingPacketCodes.EX_CRAFT_RANDOM_INFO);
        // /* D0:019B */ RegisterPacket<ExRequestRandomCraftLockSlotPacket>(IncomingPacketCodes.EX_CRAFT_RANDOM_LOCK_SLOTEX_CRAFT_RANDOM_INFO);
        // /* D0:019C */ RegisterPacket<ExRequestRandomCraftRefreshPacket>(IncomingPacketCodes.EX_CRAFT_RANDOM_REFRESH);
        // /* D0:019D */ RegisterPacket<ExRequestRandomCraftMakePacket>(IncomingPacketCodes.EX_CRAFT_RANDOM_MAKE);
        /* D0:019E */ RegisterPacket<RequestMultisellListPacket>(IncomingPacketCodes.EX_MULTI_SELL_LIST);
		// /* D0:019F */ RegisterPacket<ExSaveItemAnnounceSettingPacket>(IncomingPacketCodes.EX_SAVE_ITEM_ANNOUNCE_SETTING);
		// 270
		// /* D0:01A1 */ RegisterPacket<ExRequestSharingLocationUiPacket>(IncomingPacketCodes.EX_SHARED_POSITION_SHARING_UI);
		// /* D0:01A2 */ RegisterPacket<ExRequestSharedLocationTeleportUiPacket>(IncomingPacketCodes.EX_SHARED_POSITION_TELEPORT_UI);
		// /* D0:01A3 */ RegisterPacket<ExRequestSharedLocationTeleportPacket>(IncomingPacketCodes.EX_SHARED_POSITION_TELEPORT);
		// /* D0:01A5 */ RegisterPacket<ExPetEquipItemPacket>(IncomingPacketCodes.EX_PET_EQUIP_ITEM);
		// /* D0:01A6 */ RegisterPacket<ExPetUnequipItemPacket>(IncomingPacketCodes.EX_PET_UNEQUIP_ITEM);
		// /* D0:01AF */ RegisterPacket<ExEvolvePetPacket>(IncomingPacketCodes.EX_EVOLVE_PET);
		// /* D0:01B2 */ RegisterPacket<ExRequestTeleportFavoriteListPacket>(IncomingPacketCodes.EX_TELEPORT_FAVORITES_LIST);
		// /* D0:01B3 */ RegisterPacket<ExRequestTeleportFavoritesUITogglePacket>(IncomingPacketCodes.EX_TELEPORT_FAVORITES_UI_TOGGLE);
		// /* D0:01B4 */ RegisterPacket<ExRequestTeleportFavoritesAddDelPacket>(IncomingPacketCodes.EX_TELEPORT_FAVORITES_ADD_DEL);
		// /* D0:01C1 */ RegisterPacket<RequestBlessOptionPutItemPacket>(IncomingPacketCodes.EX_BLESS_OPTION_PUT_ITEM);
		// /* D0:01C2 */ RegisterPacket<RequestBlessOptionEnchantPacket>(IncomingPacketCodes.EX_BLESS_OPTION_ENCHANT);
		// /* D0:01C3 */ RegisterPacket<RequestBlessOptionCancelPacket>(IncomingPacketCodes.EX_BLESS_OPTION_CANCEL);
		// /* D0:01C4 */ RegisterPacket<RequestPvpRankingMyInfoPacket>(IncomingPacketCodes.EX_PVP_RANKING_MY_INFO);
		// /* D0:01C5 */ RegisterPacket<RequestPvpRankingListPacket>(IncomingPacketCodes.EX_PVP_RANKING_LIST);
		// /* D0:01C6 */ RegisterPacket<RequestExAcquirePetSkillPacket>(IncomingPacketCodes.EX_ACQUIRE_PET_SKILL);
		// /* D0:01C7 */ RegisterPacket<RequestExPledgeV3InfoPacket>(IncomingPacketCodes.EX_PLEDGE_V3_INFO);
		// /* D0:01C8 */ RegisterPacket<RequestExPledgeEnemyInfoListPacket>(IncomingPacketCodes.EX_PLEDGE_ENEMY_INFO_LIST);
		// /* D0:01C9 */ RegisterPacket<RequestExPledgeEnemyRegisterPacket>(IncomingPacketCodes.EX_PLEDGE_ENEMY_REGISTER);
		// /* D0:01CA */ RegisterPacket<RequestExPledgeEnemyDeletePacket>(IncomingPacketCodes.EX_PLEDGE_ENEMY_DELETE);
		// /* D0:01CB */ RegisterPacket<ExTryPetExtractSystemPacket>(IncomingPacketCodes.EX_TRY_PET_EXTRACT_SYSTEM);
		// /* D0:01CC */ RegisterPacket<RequestExPledgeV3SetAnnouncePacket>(IncomingPacketCodes.EX_PLEDGE_V3_SET_ANNOUNCE);
		// 306
        /* D0:01D4 */ RegisterPacket<RequestSteadyBoxLoadPacket>(IncomingPacketCodes.EX_STEADY_BOX_LOAD);
        // /* D0:01D5 */ RegisterPacket<RequestSteadyOpenSlotPacket>(IncomingPacketCodes.EX_STEADY_OPEN_SLOT);
        // /* D0:01D6 */ RegisterPacket<RequestSteadyOpenBoxPacket>(IncomingPacketCodes.EX_STEADY_OPEN_BOX);
        // /* D0:01D7 */ RegisterPacket<RequestSteadyGetRewardPacket>(IncomingPacketCodes.EX_STEADY_GET_REWARD);
        // /* D0:01D8 */ RegisterPacket<RequestPetRankingMyInfoPacket>(IncomingPacketCodes.EX_PET_RANKING_MY_INFO);
        // /* D0:01D9 */ RegisterPacket<RequestPetRankingListPacket>(IncomingPacketCodes.EX_PET_RANKING_LIST);
        /* D0:01DA */ RegisterPacket<RequestExCollectionOpenUiPacket>(IncomingPacketCodes.EX_COLLECTION_OPEN_UI);
        /* D0:01DB */ RegisterPacket<RequestExCollectionCloseUiPacket>(IncomingPacketCodes.EX_COLLECTION_CLOSE_UI);
        /* D0:01DC */ RegisterPacket<RequestExCollectionListPacket>(IncomingPacketCodes.EX_COLLECTION_LIST);
		// /* D0:01DD */ RegisterPacket<RequestCollectionUpdateFavoritePacket>(IncomingPacketCodes.EX_COLLECTION_UPDATE_FAVORITE);
		// /* D0:01DE */ RegisterPacket<RequestCollectionFavoriteListPacket>(IncomingPacketCodes.EX_COLLECTION_FAVORITE_LIST);
		// /* D0:01E0 */ RegisterPacket<RequestCollectionRegisterPacket>(IncomingPacketCodes.EX_COLLECTION_REGISTER);
		// /* D0:01E1 */ RegisterPacket<RequestCollectionReceiveRewardPacket>(IncomingPacketCodes.EX_COLLECTION_RECEIVE_REWARD);
		// /* D0:01E2 */ RegisterPacket<RequestExPvpBookShareRevengeListPacket>(IncomingPacketCodes.EX_PVPBOOK_SHARE_REVENGE_LIST);
		// /* D0:01E3 */ RegisterPacket<RequestExPvpBookShareRevengeReqShareRevengeInfoPacket>(IncomingPacketCodes.EX_PVPBOOK_SHARE_REVENGE_REQ_SHARE_REVENGEINFO);
		// /* D0:01E4 */ RegisterPacket<RequestExPvpBookShareRevengeKillerLocationPacket>(IncomingPacketCodes.EX_PVPBOOK_SHARE_REVENGE_KILLER_LOCATION);
		// /* D0:01E5 */ RegisterPacket<RequestExPvpBookShareRevengeTeleportToKillerPacket>(IncomingPacketCodes.EX_PVPBOOK_SHARE_REVENGE_TELEPORT_TO_KILLER);
		// /* D0:01E6 */ RegisterPacket<RequestExPvpBookShareRevengeSharedTeleportToKillerPacket>(IncomingPacketCodes.EX_PVPBOOK_SHARE_REVENGE_SHARED_TELEPORT_TO_KILLER);
		// /* D0:01E9 */ RegisterPacket<ExRequestUserWatcherTargetListPacket>(IncomingPacketCodes.EX_USER_WATCHER_TARGET_LIST);
		// /* D0:01EA */ RegisterPacket<ExRequestUserWatcherAddPacket>(IncomingPacketCodes.EX_USER_WATCHER_ADD);
		// /* D0:01EB */ RegisterPacket<ExRequestUserWatcherDeletePacket>(IncomingPacketCodes.EX_USER_WATCHER_DELETE);
		// /* D0:01EE */ RegisterPacket<RequestSubjugationListPacket>(IncomingPacketCodes.EX_SUBJUGATION_LIST);
		// /* D0:01EF */ RegisterPacket<RequestSubjugationRankingPacket>(IncomingPacketCodes.EX_SUBJUGATION_RANKING);
		// /* D0:01F0 */ RegisterPacket<RequestSubjugationGachaUIPacket>(IncomingPacketCodes.EX_SUBJUGATION_GACHA_UI);
		// /* D0:01F1 */ RegisterPacket<RequestSubjugationGachaPacket>(IncomingPacketCodes.EX_SUBJUGATION_GACHA);
		// /* D0:01F2 */ RegisterPacket<RequestExPledgeDonationInfoPacket>(IncomingPacketCodes.EX_PLEDGE_DONATION_INFO);
		// /* D0:01F3 */ RegisterPacket<RequestExPledgeDonationRequestPacket>(IncomingPacketCodes.EX_PLEDGE_DONATION_REQUEST);
		// /* D0:01F4 */ RegisterPacket<RequestExPledgeContributionListPacket>(IncomingPacketCodes.EX_PLEDGE_CONTRIBUTION_LIST);
		// /* D0:01F5 */ RegisterPacket<RequestPledgeRankingMyInfoPacket>(IncomingPacketCodes.EX_PLEDGE_RANKING_MY_INFO);
		// /* D0:01F6 */ RegisterPacket<RequestPledgeRankingListPacket>(IncomingPacketCodes.EX_PLEDGE_RANKING_LIST);
		// 338
		// /* D0:0207 */ RegisterPacket<RequestChangeNicknameEmotePacket>(IncomingPacketCodes.EX_CHANGE_NICKNAME_COLOR_ICON);
		// /* D0:0213 */ RegisterPacket<ExRequestPrivateStoreSearchListPacket>(IncomingPacketCodes.EX_PRIVATE_STORE_SEARCH_LIST);
		// /* D0:0214 */ RegisterPacket<ExRequestPrivateStoreSearchStatisticsPacket>(IncomingPacketCodes.EX_PRIVATE_STORE_SEARCH_STATISTICS);
        /* D0:0218 */ RegisterPacket<RequestNewHennaListPacket>(IncomingPacketCodes.EX_NEW_HENNA_LIST);
		// /* D0:0219 */ RegisterPacket<RequestNewHennaEquipPacket>(IncomingPacketCodes.EX_NEW_HENNA_EQUIP);
		// /* D0:021A */ RegisterPacket<RequestNewHennaUnequipPacket>(IncomingPacketCodes.EX_NEW_HENNA_UNEQUIP);
		// /* D0:021B */ RegisterPacket<RequestNewHennaPotenSelectPacket>(IncomingPacketCodes.EX_NEW_HENNA_POTEN_SELECT);
		// /* D0:021C */ RegisterPacket<RequestNewHennaPotenEnchantPacket>(IncomingPacketCodes.EX_NEW_HENNA_POTEN_ENCHANT);
		// /* D0:021D */ RegisterPacket<RequestNewHennaComposePacket>(IncomingPacketCodes.EX_NEW_HENNA_COMPOSE);
		// /* D0:021E */ RegisterPacket<RequestNewInvitePartyInquiryPacket>(IncomingPacketCodes.EX_REQUEST_INVITE_PARTY);
		// /* D0:0222 */ RegisterPacket<RequestHuntPassInfoPacket>(IncomingPacketCodes.EX_L2PASS_INFO);
		// /* D0:0223 */ RegisterPacket<RequestHuntPassRewardPacket>(IncomingPacketCodes.EX_L2PASS_REQUEST_REWARD);
		// /* D0:0224 */ RegisterPacket<RequestHuntPassRewardAllPacket>(IncomingPacketCodes.EX_L2PASS_REQUEST_REWARD_ALL);
		// /* D0:0225 */ RegisterPacket<RequestHuntPassBuyPremiumPacket>(IncomingPacketCodes.EX_L2PASS_BUY_PREMIUM);
		// /* D0:0226 */ RegisterPacket<HuntpassSayhasTogglePacket>(IncomingPacketCodes.EX_SAYHAS_SUPPORT_TOGGLE);
		// 362
		// /* D0:0227 */ RegisterPacket<ExRequestEnchantFailRewardInfoPacket>(IncomingPacketCodes.EX_REQ_ENCHANT_FAIL_REWARD_INFO);
		// /* D0:0228 */ RegisterPacket<ExRequestSetEnchantChallengePointPacket>(IncomingPacketCodes.EX_SET_ENCHANT_CHALLENGE_POINT);
		// /* D0:0229 */ RegisterPacket<ExRequestResetEnchantChallengePointPacket>(IncomingPacketCodes.EX_RESET_ENCHANT_CHALLENGE_POINT);
		// /* D0:022A */ RegisterPacket<ExRequestViewEnchantResultPacket>(IncomingPacketCodes.EX_REQ_VIEW_ENCHANT_RESULT);
		// /* D0:022B */ RegisterPacket<ExRequestStartMultiEnchantScrollPacket>(IncomingPacketCodes.EX_REQ_START_MULTI_ENCHANT_SCROLL);
		// /* D0:022C */ RegisterPacket<ExRequestViewMultiEnchantResultPacket>(IncomingPacketCodes.EX_REQ_VIEW_MULTI_ENCHANT_RESULT);
		// /* D0:022D */ RegisterPacket<ExRequestFinishMultiEnchantScrollPacket>(IncomingPacketCodes.EX_REQ_FINISH_MULTI_ENCHANT_SCROLL);
		// /* D0:022F */ RegisterPacket<ExRequestSetMultiEnchantItemListPacket>(IncomingPacketCodes.EX_REQ_SET_MULTI_ENCHANT_ITEM_LIST);
		// /* D0:0230 */ RegisterPacket<ExRequestMultiEnchantItemListPacket>(IncomingPacketCodes.EX_REQ_MULTI_ENCHANT_ITEM_LIST);
        /* D0:0236 */ RegisterPacket<RequestMissionRewardListPacket>(IncomingPacketCodes.EX_MISSION_LEVEL_REWARD_LIST);
        // /* D0:0237 */ RegisterPacket<RequestMissionLevelReceiveRewardPacket>(IncomingPacketCodes.EX_MISSION_LEVEL_RECEIVE_REWARD);
        // /* D0:0238 */ RegisterPacket<ExBalrogWarTeleportPacket>(IncomingPacketCodes.EX_BALROGWAR_TELEPORT);
        // /* D0:0239 */ RegisterPacket<ExBalrogWarShowUIPacket>(IncomingPacketCodes.EX_BALROGWAR_SHOW_UI);
        // /* D0:023A */ RegisterPacket<ExBalrogWarShowRankingPacket>(IncomingPacketCodes.EX_BALROGWAR_SHOW_RANKING);
        // /* D0:023B */ RegisterPacket<ExBalrogWarGetRewardPacket>(IncomingPacketCodes.EX_BALROGWAR_GET_REWARD);
        // /* D0:023D */ RegisterPacket<ExWorldExchangeItemListPacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_ITEM_LIST);
        // /* D0:023E */ RegisterPacket<ExWorldExchangeRegisterItemPacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_REGI_ITEM);
        // /* D0:023F */ RegisterPacket<ExWorldExchangeBuyItemPacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_BUY_ITEM);
        // /* D0:0240 */ RegisterPacket<ExWorldExchangeSettleListPacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_SETTLE_LIST);
        // /* D0:0241 */ RegisterPacket<ExWorldExchangeSettleRecvResultPacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_SETTLE_RECV_RESULT);
        // /* D0:0242 */ RegisterPacket<ExRequestReadyItemAutoPeelPacket>(IncomingPacketCodes.EX_READY_ITEM_AUTO_PEEL);
        // /* D0:0243 */ RegisterPacket<ExRequestItemAutoPeelPacket>(IncomingPacketCodes.EX_REQUEST_ITEM_AUTO_PEEL);
        // /* D0:0244 */ RegisterPacket<ExRequestStopItemAutoPeelPacket>(IncomingPacketCodes.EX_STOP_ITEM_AUTO_PEEL);
        // /* D0:0245 */ RegisterPacket<ExVariationOpenUiPacket>(IncomingPacketCodes.EX_VARIATION_OPEN_UI);
        // /* D0:0246 */ RegisterPacket<ExVariationCloseUiPacket>(IncomingPacketCodes.EX_VARIATION_CLOSE_UI);
        // /* D0:0247 */ RegisterPacket<ExApplyVariationOptionPacket>(IncomingPacketCodes.EX_APPLY_VARIATION_OPTION);
        /* D0:0249 */ RegisterPacket<RequestBRVersionPacket>(IncomingPacketCodes.EX_BR_VERSION).WithAllowedStates(GameSessionState.Authorization | GameSessionState.CharacterScreen);
        // 388
        // /* D0:0251 */ RegisterPacket<RequestNewHennaUnequipInfoPacket>(IncomingPacketCodes.EX_HENNA_UNEQUIP_INFO);
        /* D0:0254 */ RegisterPacket<RequestExTeleportUiPacket>(IncomingPacketCodes.EX_TELEPORT_UI);
		// /* D0:0258 */ RegisterPacket<ExWorldExchangeAveragePricePacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_AVERAGE_PRICE);
		// /* D0:0259 */ RegisterPacket<ExWorldExchangeTotalListPacket>(IncomingPacketCodes.EX_WORLD_EXCHANGE_TOTAL_LIST);
		// 414
		// /* D0:0262 */ RegisterPacket<RequestSetPledgeCrestPresetPacket>(IncomingPacketCodes.EX_SET_PLEDGE_CREST_PRESET);
		// /* D0:0263 */ RegisterPacket<RequestGetPledgeCrestPresetPacket>(IncomingPacketCodes.EX_GET_PLEDGE_CREST_PRESET);
		// /* D0:0264 */ RegisterPacket<RequestExDualInventorySwapPacket>(IncomingPacketCodes.EX_DUAL_INVENTORY_SWAP);
		// /* D0:0265 */ RegisterPacket<RequestExSpExtractInfoPacket>(IncomingPacketCodes.EX_SP_EXTRACT_INFO);
		// /* D0:0266 */ RegisterPacket<RequestExSpExtractItemPacket>(IncomingPacketCodes.EX_SP_EXTRACT_ITEM);
		// /* D0:0267 */ RegisterPacket<RequestExQuestTeleportPacket>(IncomingPacketCodes.EX_QUEST_TELEPORT);
		// /* D0:0268 */ RegisterPacket<RequestExQuestAcceptPacket>(IncomingPacketCodes.EX_QUEST_ACCEPT);
		// /* D0:0269 */ RegisterPacket<RequestExQuestCancelPacket>(IncomingPacketCodes.EX_QUEST_CANCEL);
		// /* D0:026A */ RegisterPacket<RequestExQuestCompletePacket>(IncomingPacketCodes.EX_QUEST_COMPLETE);
		// /* D0:026B */ RegisterPacket<RequestExQuestNotificationAllPacket>(IncomingPacketCodes.EX_QUEST_NOTIFICATION_ALL);
		// /* D0:026C */ RegisterPacket<RequestExQuestUIPacket>(IncomingPacketCodes.EX_QUEST_UI);
		// /* D0:026D */ RegisterPacket<RequestExQuestAcceptableListPacket>(IncomingPacketCodes.EX_QUEST_ACCEPTABLE_LIST);
		// /* D0:026E */ RegisterPacket<RequestExSkillEnchantInfoPacket>(IncomingPacketCodes.EX_SKILL_ENCHANT_INFO);
		// /* D0:026F */ RegisterPacket<RequestExSkillEnchantChargePacket>(IncomingPacketCodes.EX_SKILL_ENCHANT_CHARGE);
		// 430
		// /* D0:027A */ RegisterPacket<RequestVipAttendanceItemListPacket>(IncomingPacketCodes.EX_VIP_ATTENDANCE_LIST);
		// /* D0:027B */ RegisterPacket<RequestVipAttendanceCheckPacket>(IncomingPacketCodes.EX_VIP_ATTENDANCE_CHECK);
		// /* D0:027C */ RegisterPacket<RequestVipAttendanceItemRewardPacket>(IncomingPacketCodes.EX_VIP_ATTENDANCE_REWARD);
		// /* D0:027E */ RegisterPacket<ExRequestNewHennaEnchantResetPacket>(IncomingPacketCodes.EX_NEW_HENNA_POTEN_ENCHANT_RESET);
		// 439
		// 447
    }

    protected override bool OnPacketInvalidState(Connection connection, GameSession session)
    {
        GameSessionState currentState = session.State;
        if (currentState != GameSessionState.InGame)
        {
            AuthLoginFailedPacket authLoginFailedPacket = new(0, AuthFailedReason.AccessFailedTryLater);
            connection.Send(ref authLoginFailedPacket, SendPacketOptions.CloseAfterSending);
        }
        else
            connection.Close();

        return false;
    }
}